Repository raiden-network/raiden, pull requests merged in 2018-12, with the labels that each got.

#3102 Disable coverage on long running integration tests
  .travis.yml
Labels: dev: Please Review

#3107 Abstract away common initiator unit tests setup
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
Labels: dev: Please Review

#3112 Detect and fix mypy errors about Address type
  Makefile
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/target.py
  raiden/utils/__init__.py
Labels: dev: Please Review

#3119 Reject secret reveal
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
  raiden/tests/utils/factories.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#3129 Remove node requirement from install guide
  docs/macos_install_guide.rst
Labels: dev: Please Review

#3131 Remove compile_webui from travis configuration
  .travis.yml
  docker/build.Dockerfile
Labels: dev: Please Review

#3109 [debug tool] Add json log to html formatting helper tool
  requirements-dev.txt
  tools/debugging/json-log-to-html.py
Labels: dev: Please Review

#3115 Remove raiden/tests/smart_contracts from tox.ini
  tox.ini
Labels: dev: Please Review

#3136 Fix html rendering event filtering
  tools/debugging/json-log-to-html.py
Labels: dev: Please Review

#3134 Add docstrings in balanceproof.py + kwargs
  raiden/raiden_event_handler.py
  raiden/transfer/balance_proof.py
Labels: dev: Please Review

#3141 More descriptive event log name for matrix account data get
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#3142 Fix "Deposit amount decreased" crash in development mode
  docs/changelog.rst
  raiden/api/python.py
  raiden/network/proxies/token_network.py
  raiden/tests/integration/cli/conftest.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/utils/smoketest.py
  raiden/ui/app.py
  raiden/ui/cli.py
Labels: dev: Please Review

#3128 Update scenario player
  tools/scenario-player/example-scenarios/scenario-example-v2.yaml
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/tasks/base.py
  tools/scenario-player/scenario_player/tasks/raiden_api.py
  tools/scenario-player/scenario_player/tasks/raiden_node.py
Labels: dev: Please Review, scenario player

#3159 Add v prefix to api version
  docs/api_walkthrough.rst
  docs/changelog.rst
  docs/rest_api.rst
  raiden/api/rest.py
  raiden/tests/integration/api/test_restapi.py
  raiden/tests/utils/smoketest.py
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/tasks/token_network.py
Labels: dev: Please Review

#3164 Fix CircleCI timeout with parallelism=1 by increasing to 2
  .circleci/config.yml
Labels: dev: Please Review, infrastructure, testing

#3166 Bump to v0.19.0
  .bumpversion_client.cfg
  docs/changelog.rst
  docs/conf.py
  setup.py
Labels: dev: Please Review

#3162 Replay WAL debugging script
  tools/debugging/replay_wal.py
Labels: dev: Please Review

#3168 Mediator task handling of invalid refund transfer
  docs/changelog.rst
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#3176 Do not crash at check_version if github request returns unexpected data
  docs/changelog.rst
  raiden/tasks.py
  raiden/tests/unit/test_version_check.py
Labels: dev: Please Review

#3181 SendRefundTransfer should have a balance_proof attribute
  docs/changelog.rst
  raiden/tests/unit/test_sqlite.py
  raiden/tests/unit/transfer/mediated_transfer/test_events.py
  raiden/transfer/mediated_transfer/events.py
Labels: dev: Please Review

#3182 Remove outdated state change from WAL replay script and add some useful filter functions
  tools/debugging/replay_wal.py
Labels: dev: Please Review

#3180 Matrix: handle E500 on join_room
  raiden/network/transport/matrix.py
  raiden/tests/integration/test_matrix_transport.py
Labels: dev: Please Review, matrix

#3127 New workflow for release deployment only
  .circleci/config.yml
  tools/debugging/replay_wal.py
Labels: dev: Please Review, infrastructure

#3174 Remove information about the debugging endpoints from the docs
  docs/rest_api.rst
Labels: dev: Please Review

#3188 Add pgp key and document process
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  raiden_errors_key.gpg
Labels: dev: Please Review

#3192 Add changelog for 3171
  docs/changelog.rst
Labels: dev: Please Review

#3195 Add privacy policy for sent logs
  CONTRIBUTING.md
Labels: dev: Please Review

#3194 Channel balance returned by API takes locked amount into account
  docs/changelog.rst
  raiden/api/v1/encoding.py
Labels: dev: Please Review

#3197 Unlock using state change or event
  docs/changelog.rst
  raiden/raiden_event_handler.py
  raiden/storage/sqlite.py
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/utils.py
Labels: dev: Please Review

#3198 Red bump
  .bumpversion_client.cfg
  docs/changelog.rst
  docs/conf.py
  raiden/ui/app.py
  raiden/ui/cli.py
  setup.py
Labels: dev: Please Review

#1556 write initial version of simple Red Eyes tutorial
  docs/index.rst
  docs/red_eyes_mainnet_tutorial.rst
Labels: dev: Please Review, documentation

#3202 Fix red eyes version in changelog
  docs/changelog.rst
Labels: dev: Please Review

#3207 Upgrade to flake8 3.6.0 and fix violations
  raiden/blockchain_events_handler.py
  raiden/storage/restore.py
  raiden/storage/versions.py
  raiden/tests/integration/test_matrix_transport.py
  raiden/utils/cli.py
  requirements-lint.txt
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review

#3206 Workaround for Infura and gas price strategy issue
  docs/changelog.rst
  raiden/network/rpc/client.py
Labels: dev: Please Review

#3189 Add translator to WAL replay tool
  tools/debugging/replay_wal.py
Labels: dev: Please Review

#3208 Fix build due to flake8 lint error
  tools/debugging/replay_wal.py
Labels: dev: Please Review
