Repository raiden-network/raiden, pull requests merged in 2018-07, with the labels that each got.

#1702 Skip test_echo_node.py::test_event_transfer_received_success if not udp
  raiden/tests/integration/test_echo_node.py
Labels: dev: Please Review, testing

#1696 Secret reveal tests
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#1712 Fix `skip_if_not_udp` fixture
  raiden/tests/integration/fixtures/transport.py
Labels: dev: Please Review

#1714 Fix leaving a token network
  raiden/api/python.py
Labels: dev: Please Review

#1717 use different words for blockchain and raiden events logging
  raiden/blockchain_events_handler.py
  raiden/raiden_service.py
Labels: dev: Please Review

#1716 added missing dunder methods
  raiden/transfer/state_change.py
Labels: dev: Please Review

#1729 Add token_network_identifier arg to get_channel_events_for_token
  raiden/tests/utils/events.py
  raiden/utils/echo_node.py
Labels: dev: Please Review

#1730 Readd the skipping of integration tests in most builds
  .travis.yml
Labels: dev: Please Review

#1732 Readd vanished channelstate unit tests
  raiden/tests/unit/test_channelstate.py
Labels: dev: Please Review

#1735 Fixed the call to settle
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#1725 Add token limit
  raiden/api/python.py
  raiden/api/rest.py
  raiden/exceptions.py
  raiden/tests/integration/api/test_restapi.py
Labels: dev: Please Review

#1737 added failling test case for #1736
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
Labels: dev: Please Review

#1719 Improve error handling of the REST api
  raiden/api/rest.py
  raiden/api/v1/encoding.py
Labels: dev: Please Review

#1742 Fix contract names in the check_address_has_code checks
  raiden/network/proxies/secret_registry.py
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#1741 made geth the default blockchain
  raiden/tests/conftest.py
Labels: dev: Please Review

#1744 disable pytest's captlogs if --log-config is used
  raiden/tests/conftest.py
Labels: dev: Please Review

#1746 Pin jquery to ^3.0.0
  raiden/ui/web/package.json
Labels: dev: Please Review

#1740 bugfix: ChannelOpened replay must not overwrite the channel
  raiden/tests/unit/test_tokennetwork.py
  raiden/transfer/token_network.py
Labels: dev: Please Review

#1753 Use Python 3.6 on ReadTheDocs [skip ci]
  readthedocs.yml
Labels: dev: Please Review

#1758 Fix integration tests
  raiden/tests/utils/smartcontracts.py
Labels: dev: Please Review

#1766 Fix parameter name for a view
  raiden/transfer/views.py
Labels: dev: Please Review

#1764 Ensure matrix.log property returns a logger even if called on __init__
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#1767 Handle EventTransferReceivedInvalidDirectTransfer by ignoring
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#1770 Allow '~' in config file also for `File` type options
  raiden/ui/cli.py
Labels: dev: Please Review

#1771 --pdb ignore BdbQuit exception
  raiden/tests/conftest.py
Labels: dev: Please Review

#1772 Some typing fixes in tests/utils/smartcontracts.py
  raiden/tests/utils/smartcontracts.py
Labels: dev: Please Review

#1775 Fix channel_identifier in test_events.py::test_query_events
  raiden/tests/integration/test_events.py
  raiden/utils/netting_channel.py
Labels: dev: Please Review

#1754 fixed test_endpointregistry_gas test
  raiden/constants.py
  raiden/tests/integration/test_endpointregistry.py
Labels: dev: Please Review

#1755 using raiden-contract's precompiled contracts
  raiden/tests/integration/contracts/fixtures/contracts.py
  raiden/tests/utils/smartcontracts.py
Labels: dev: Please Review

#1781 Provide a proper error if DB contains invalid data
  raiden/exceptions.py
  raiden/storage/sqlite.py
  raiden/ui/cli.py
Labels: dev: Please Review

#1782 Link new contracts in README
  README.rst
Labels: dev: Please Review

#1789 Set query_start_block depending on the network identifier
  raiden/api/v1/resources.py
  raiden/app.py
  raiden/constants.py
  raiden/raiden_service.py
  raiden/tests/benchmark/speed_simulation.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/utils/network.py
  raiden/ui/cli.py
  tools/scenario_runner.py
Labels: dev: Please Review

#1795 Log message sending at info level
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#1799 Add experimental software disclaimer
  raiden/ui/cli.py
Labels: dev: Please Review

#1801 WebUI: bring back channel identifier and some icons
  raiden/ui/web/src/app/components/channel-table/channel-table.component.html
  raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
Labels: dev: Please Review

#1803 Fix and test channel events endpoint
  raiden/api/rest.py
  raiden/tests/integration/api/test_restapi.py
Labels: dev: Please Review

#1806 Temporarily remove the token swaps from the WebUI
  raiden/ui/web/src/app/components/token-network/token-network.component.html
Labels: dev: Please Review

#1808 upgrade raiden-libs
  requirements.txt
  setup.py
Labels: dev: Please Review

#1804 Raiden must use a single TokenNetworkProxy per TN
  raiden/api/python.py
  raiden/api/rest.py
  raiden/blockchain_events_handler.py
  raiden/exceptions.py
  raiden/network/proxies/token_network.py
  raiden/network/proxies/token_network_registry.py
  raiden/tests/integration/contracts/test_network_registry.py
  raiden/tests/integration/test_blockchainservice.py
  raiden/tests/integration/test_events.py
  raiden/tests/utils/network.py
Labels: dev: Please Review

#1824 Fix block number at sync check
  raiden/network/blockchain_service.py
Labels: dev: Please Review

#1721 Add registerSecretBatch to contract proxy
  raiden/network/proxies/secret_registry.py
  raiden/tests/integration/contracts/test_secret_registry.py
Labels: dev: Please Review

#1827 fix test_query_events
  raiden/tests/integration/test_events.py
Labels: dev: Please Review

#1833 fixed conflict module names
  raiden/tests/integration/test_integration_events.py
  raiden/tests/unit/api/test_api_events.py
Labels: dev: Please Review

#1828 Increase gas prices for ropsten by factor two
  raiden/constants.py
  raiden/network/rpc/client.py
Labels: dev: Please Review

#1835 Add comment explaining why filters are queried at installation
  raiden/raiden_service.py
Labels: dev: Please Review

#1832 Return HTTP 202 Accepted for endpoints when timeouts are reached
  docs/rest_api.rst
  raiden/api/rest.py
Labels: dev: Please Review

#1842 Update raiden-libs
  requirements.txt
  setup.py
Labels: dev: Please Review

#1845 function update_contract_balance was not being used
  raiden/transfer/channel.py
Labels: dev: Please Review

#1846 cleanup utils
  raiden/utils/__init__.py
Labels: dev: Please Review

#1851 removed unecessary mocks
  raiden/tests/unit/test_cli.py
Labels: dev: Please Review

#1850 removed unused views
  raiden/transfer/views.py
Labels: dev: Please Review

#1853 removed ChannelList
  raiden/api/objects.py
Labels: dev: Please Review

#1856 removed unused exception
  raiden/exceptions.py
Labels: dev: Please Review

#1857 removed unused attributes & functions
  raiden/network/blockchain_service.py
  raiden/network/proxies/token_network_registry.py
  raiden/network/rpc/client.py
Labels: dev: Please Review

#1854 clean up messages
  raiden/encoding/messages.py
  raiden/encoding/signing.py
  raiden/messages.py
Labels: dev: Please Review

#1838 Mention account ownership requirements in the docs
  docs/overview_and_guide.rst
Labels: dev: Please Review

#1849 More logging cleanup in token network proxy
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#1848 console cleanup
  raiden/app.py
  raiden/ui/console.py
Labels: dev: Please Review

#1864 Fix Logging at ContractReceivechannelbatchunlock
  raiden/transfer/state_change.py
Labels: dev: Please Review

#1873 Fix #1794
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#1875 Fix #1874
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#1881 Ignore messages not signed by sender
  raiden/network/transport/matrix.py
Labels: dev: Please Review, matrix

#1880 Handle unreachable matrix servers and disconnects more graceful
  raiden/app.py
  raiden/exceptions.py
  raiden/network/transport/matrix.py
  raiden/network/utils.py
  raiden/ui/cli.py
  raiden/utils/gevent.py
Labels: dev: Please Review

#1884 Fix token network clean up
  raiden/tests/unit/test_tokennetwork.py
  raiden/transfer/token_network.py
Labels: dev: Please Review

#1890 Add 402 Insufficient fund error to the API docs
  docs/rest_api.rst
Labels: dev: Please Review

#1905 Move mirakuru from dev to runtime deps
  requirements-dev.txt
  requirements.txt
Labels: dev: Please Review

#1909 Add httpexample files to _static
  docs/_static/sphinxcontrib-httpexample.css
  docs/_static/sphinxcontrib-httpexample.js
Labels: dev: Please Review

#1920 fixed raiden.utils import when running pytest
  raiden/app.py
  raiden/tests/integration/__init__.py
  raiden/tests/integration/contracts/__init__.py
  raiden/tests/integration/rpc/__init__.py
  raiden/tests/integration/transfer/__init__.py
  raiden/tests/unit/api/__init__.py
  raiden/ui/cli.py
  raiden/utils/gevent_utils.py
Labels: dev: Please Review

#1923 Serially send queued messages to prevent absue of the connection pool
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#1933 nicer formating for the sync message
  raiden/constants.py
  raiden/ui/cli.py
Labels: dev: Please Review

#1934 Update raiden-libs
  requirements.txt
  setup.py
Labels: dev: Please Review

#1946 Add changelog entry for matrix improvements
  docs/changelog.rst
Labels: dev: Please Review

#1952 Fix automatic travis building of linux bundle
  Makefile
  docker/build.Dockerfile
  raiden/utils/__init__.py
  setup.py
Labels: dev: Please Review

#1954 Add leading underscore for private class members to contributing.md
  CONTRIBUTING.md
Labels: dev: Please Review

#1959 Return E409 on concurrent deposits
  docs/changelog.rst
  docs/rest_api.rst
  raiden/api/rest.py
  raiden/exceptions.py
  raiden/network/proxies/token_network.py
  raiden/tests/integration/contracts/test_token_network.py
Labels: dev: Please Review

#1961 Check if token network exists when opening a channel
  docs/changelog.rst
  raiden/api/python.py
  raiden/api/rest.py
  raiden/exceptions.py
Labels: dev: Please Review

#1978 Fix hash_balance_data
  docs/changelog.rst
  raiden/tests/unit/transfer/test_utils.py
  raiden/transfer/utils.py
Labels: dev: Please Review

#1985 Fix automatic macOS bundling by adding a missing dependency
  .travis/prepare_os_osx.sh
  docs/macos_install_guide.rst
Labels: dev: Please Review

#1958 Remove only_receiving parameter from leave network API
  docs/api_walkthrough.rst
  docs/rest_api.rst
  raiden/api/python.py
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/api/v1/resources.py
  raiden/connection_manager.py
Labels: dev: Please Review

#1988 Add changelog entry for 1879
  docs/changelog.rst
Labels: dev: Please Review

#1929 Security alert message
  docs/changelog.rst
  raiden/tasks.py
  raiden/tests/unit/test_version_check.py
Labels: dev: Please Review

#1868 Add debug file logger
  docs/changelog.rst
  raiden/log_config.py
  raiden/tests/unit/test_logging.py
Labels: dev: Please Review

#1992 Release 0.4.1
  .bumpversion_client.cfg
  docs/conf.py
  setup.py
Labels: dev: Please Review

#1989 added type information for transfer/channel.py
  raiden/transfer/node.py
Labels: dev: Please Review

#1995 Add db versioning and fix corrupt connect
  docs/changelog.rst
  raiden/storage/sqlite.py
  raiden/storage/utils.py
  raiden/storage/wal.py
  raiden/tests/unit/test_wal.py
Labels: dev: Please Review

#2002 Fix travis stage conditions
  .travis.yml
Labels: dev: Please Review, testing

#2007 Contract address presets for multiple chain ids
  raiden/constants.py
  raiden/ui/cli.py
Labels: dev: Please Review

#2005 remove unused state change
  raiden/transfer/state_change.py
Labels: dev: Please Review

#2001 Add contract tests to unit test run
  .travis.yml
  .travis/run.sh
Labels: dev: Please Review

#2010 Mention debug file in issue template
  .github/ISSUE_TEMPLATE
Labels: dev: Please Review

#1962 Perform check on channel identifier in close, update, settle and unlock
  raiden/exceptions.py
  raiden/network/proxies/payment_channel.py
  raiden/network/proxies/token_network.py
  raiden/raiden_event_handler.py
  raiden/tests/integration/contracts/test_payment_channel.py
  raiden/tests/integration/contracts/test_token_network.py
Labels: dev: Please Review

#2009 Removes timeouts for onchain calls of the REST API
  raiden/api/python.py
Labels: dev: Please Review

#2013 Add annotations to raiden.api.python
  raiden/api/python.py
Labels: dev: Please Review

#2006 Check settle data before sending the settle tx
  raiden/constants.py
  raiden/network/proxies/token_network.py
  raiden/raiden_event_handler.py
  raiden/tests/integration/contracts/test_token_network.py
  raiden/tests/unit/transfer/test_utils.py
  raiden/transfer/utils.py
Labels: dev: Please Review

#2023 Fix pip install requirements for raiden libs
  requirements.txt
Labels: dev: Please Review

#2024 Fix logging if debug logfile is disabled
  raiden/log_config.py
Labels: dev: Please Review
