Repository raiden-network/raiden, pull requests merged in 2018-08, with the labels that each got.

#2025 Fix test_cli_registry_address_without_deployed_contract
  raiden/tests/integration/cli/test_cli.py
Labels: dev: Please Review

#2026 Test logging with --disable-debug-log
  raiden/log_config.py
  raiden/tests/unit/test_logging.py
Labels: dev: Please Review

#2019 added start check for the wrapper classes
  raiden/api/python.py
  raiden/api/rest.py
Labels: dev: Please Review

#2028 Fix the way ChannelOutdatedError is being logged
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#2015 Fix and unskip test_participant_selection
  raiden/connection_manager.py
  raiden/tests/integration/long_running/flaky/__init__.py
  raiden/tests/integration/long_running/test_token_networks.py
Labels: dev: Please Review, testing

#2047 Fix linux bundle creation
  docker/build.Dockerfile
Labels: dev: Please Review

#2048 Bump raiden libs dependency to v0.1.2
  requirements.txt
  setup.py
Labels: dev: Please Review

#2053 Check that total_deposit is not None
  raiden/api/rest.py
Labels: dev: Please Review

#2055 Fix release links in changelog
  docs/conf.py
Labels: dev: Please Review

#2065 Removed flaky
  requirements-dev.txt
Labels: dev: Please Review

#2064 JSONRPCClient nonce simplification
  raiden/network/rpc/client.py
Labels: dev: Please Review

#2072 Python API: don't check if Raiden is running
  raiden/api/python.py
Labels: dev: Please Review

#2067 Fixed race for proxies instantiation
  raiden/network/blockchain_service.py
Labels: dev: Please Review

#2020 Multiple NettingChannelStates
  raiden/tests/integration/api/test_pythonapi.py
  raiden/tests/integration/test_integration_events.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_settlement.py
  raiden/tests/integration/transfer/test_directransfer.py
  raiden/tests/integration/transfer/test_directransfer_invalid.py
  raiden/tests/integration/transfer/test_mediatedtransfer.py
  raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/tests/unit/conftest.py
  raiden/tests/unit/fixtures.py
  raiden/tests/unit/test_channelstate.py
  raiden/tests/unit/test_tokennetwork.py
  raiden/tests/utils/transfer.py
  raiden/transfer/channel.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/transfer/token_network.py
  raiden/transfer/views.py
Labels: dev: Please Review

#2079 Increased pytest reporting detail
  .travis/run.sh
Labels: dev: Please Review

#2050 update api walkthrough doc
  docs/api_walkthrough.rst
Labels: dev: Please Review

#2080 Add logging for WAL and state replay
  raiden/raiden_service.py
  raiden/storage/wal.py
Labels: dev: Please Review

#2089 fix changelog for #1984
  docs/changelog.rst
Labels: dev: Please Review

#2091 fixed call to _get_channels_close_events
  raiden/transfer/node.py
Labels: dev: Please Review

#2092 Removes eth-endpoint_to_hostport helper
  raiden/utils/__init__.py
Labels: dev: Please Review

#2061 Use EthAuthProvider in synapse
  tools/eth_auth_provider.py2
  tools/install_synapse.sh
  tools/synapse-config.yaml
Labels: dev: Please Review, matrix, testing

#2095 Add payment and transfer to the Glossary
  docs/glossary.rst
Labels: dev: Please Review

#2073 Check token balance before joining a token network
  raiden/connection_manager.py
Labels: dev: Please Review

#2098 Fix requests connection adapter issue
  raiden/ui/cli.py
Labels: dev: Please Review

#2102 Fix routing through unavailable channels
  raiden/routing.py
  raiden/transfer/views.py
Labels: dev: Please Review

#2106 add where to start paragraph and update what is Raiden
  docs/index.rst
Labels: dev: Please Review

#2115 allow multiple snapshots
  raiden/storage/sqlite.py
  raiden/storage/wal.py
  raiden/tests/unit/test_wal.py
Labels: dev: Please Review

#2104 Added pylint check for missing function arguments
  Makefile
  raiden/__main__.py
  raiden/main.py
  raiden/transfer/utils.py
  requirements-lint.txt
Labels: dev: Please Review

#2087 Improve connection manager connection retry
  raiden/blockchain_events_handler.py
Labels: dev: Please Review

#2121 removed pytest --tb=long
  .travis/run.sh
Labels: dev: Please Review

#2112 Transaction queue fixes
  raiden/transfer/node.py
  raiden/transfer/state_change.py
Labels: dev: Please Review

#2122 Followup from 2041 -- got a lot more children of _AbstractLinkable
  raiden/connection_manager.py
  raiden/network/proxies/secret_registry.py
  raiden/network/proxies/token_network.py
  raiden/network/transport/matrix.py
  raiden/network/transport/udp/udp_transport.py
  raiden/network/transport/udp/udp_utils.py
  raiden/raiden_service.py
  raiden/tasks.py
  raiden/tests/utils/tester.py
  raiden/ui/cli.py
  raiden/utils/echo_node.py
  raiden/utils/gevent_utils.py
  raiden/utils/notifying_queue.py
  tools/scenario_runner.py
Labels: dev: Please Review

#2113 Transaction queue handle races
  raiden/transfer/node.py
Labels: dev: Please Review

#2114 Solved events serialization problem
  raiden/api/rest.py
  raiden/tests/integration/api/test_restapi.py
Labels: dev: Please Review

#2132 Fix test_echo_node by tweaking settle and reveal timeouts
  raiden/tests/integration/test_echo_node.py
Labels: dev: Please Review, testing

#2126 Update gas requirements for new contracts
  raiden/constants.py
Labels: dev: Please Review

#2145 Fix 2144 - usage of queue_identifier in _send_queued_messages
  raiden/network/transport/matrix.py
  raiden/network/transport/udp/udp_transport.py
Labels: dev: Please Review

#2148 removed unused encoder
  raiden/encoding/encoders.py
Labels: dev: Please Review

#2083 Snapshot every configured number of blocks
  docs/changelog.rst
  raiden/constants.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2147 removed unused DEFAULT_POLL_TIMEOUT setting
  raiden/settings.py
Labels: dev: Please Review

#2150 Simplify identifier_to_results and remove assert
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2142 Handle 404 when User.get_display_name, better caching on join discovery room
  raiden/network/transport/matrix.py
Labels: dev: Please Review, matrix

#2151 properly handling communication exception
  raiden/ui/cli.py
Labels: dev: Please Review

#2158 Fix identifier to results
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#2162 Simplify payment channel unlock filter
  raiden/blockchain/events.py
  raiden/network/proxies/payment_channel.py
  raiden/tests/integration/contracts/test_payment_channel.py
Labels: dev: Please Review

#2154 display error message when geth goes offline
  raiden/ui/cli.py
Labels: dev: Please Review

#2172 Clean expired transactions
  raiden/transfer/architecture.py
  raiden/transfer/channel.py
  raiden/transfer/events.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/target.py
  raiden/transfer/node.py
  raiden/transfer/secret_registry.py
Labels: dev: Please Review

#2178 Test unlock state pruning
  raiden/tests/unit/test_tokennetwork.py
Labels: dev: Please Review

#2181 use payment instead of transfer in the docs
  docs/api_walkthrough.rst
  docs/overview_and_guide.rst
  docs/rest_api.rst
  docs/webui_tutorial.rst
Labels: dev: Please Review

#2184 Remove duplicate type for token network identifer
  raiden/transfer/mediated_transfer/state.py
  raiden/transfer/state.py
  raiden/transfer/state_change.py
  raiden/transfer/views.py
  raiden/utils/typing.py
Labels: dev: Please Review

#2196 Crash Rest API if unhandled exception happens on request
  raiden/api/rest.py
  raiden/tests/integration/api/fixtures.py
  raiden/tests/integration/api/test_restapi.py
Labels: API, dev: Please Review, testing

#2202 Removed address_by_endpoint from the proxies
  raiden/network/discovery.py
  raiden/network/proxies/discovery.py
  raiden/tests/integration/test_endpointregistry.py
  raiden/tests/unit/test_mock.py
Labels: dev: Please Review

#2191 Test queued messages send on restart
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/waiting.py
Labels: dev: Please Review

#2204 Fix automatic deployment
  .travis.yml
Labels: dev: Please Review

#2171 Revisit gevent exception handling
  CONTRIBUTING.md
  raiden/app.py
  raiden/connection_manager.py
  raiden/exceptions.py
  raiden/network/proxies/secret_registry.py
  raiden/network/proxies/token_network.py
  raiden/network/transport/matrix.py
  raiden/network/transport/udp/udp_transport.py
  raiden/network/transport/udp/udp_utils.py
  raiden/raiden_service.py
  raiden/tasks.py
  raiden/tests/conftest.py
  raiden/tests/unit/test_utils.py
  raiden/tests/utils/tester.py
  raiden/ui/cli.py
  raiden/ui/console.py
  raiden/utils/echo_node.py
  raiden/utils/gevent_utils.py
  raiden/utils/notifying_queue.py
Labels: dev: Please Review

#2203 Send secret reveal once
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review

#2180 Fix typo in ContractSendChannelBatchUnlock
  raiden/raiden_event_handler.py
  raiden/transfer/events.py
Labels: :warning: Breaking change, dev: Please Review

#2212 Fix `from` key missing from tx receipt by getting it from tx directly
  raiden/network/rpc/client.py
Labels: dev: Please Review

#2190 Store tx hashes
  raiden/blockchain_events_handler.py
  raiden/constants.py
  raiden/raiden_service.py
  raiden/tests/unit/test_channelstate.py
  raiden/tests/unit/test_tokennetwork.py
  raiden/tests/unit/test_wal.py
  raiden/tests/utils/factories.py
  raiden/transfer/architecture.py
  raiden/transfer/state_change.py
  raiden/utils/typing.py
Labels: :warning: Breaking change, dev: Please Review

#2200 Added database version
  raiden/ui/cli.py
Labels: :warning: Breaking change, dev: Please Review

#2215 target emit unlock failed only once
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review

#2210 Fix building the webui in the automated deployment
  .travis.yml
  MANIFEST.in
  docker/build.Dockerfile
  setup.py
Labels: dev: Please Review

#2228 fixing example responses, typos and missing json fields
  docs/rest_api.rst
Labels: dev: Please Review

#2235 Handle json decode error when matrix display name is invalid
  raiden/network/transport/matrix.py
Labels: dev: Please Review, matrix

#2243 Add v0.5.1 and user-facing changes to the changelog
  docs/changelog.rst
Labels: dev: Please Review

#2244 fix call to log.error
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#2250 Add missing changelog entries for Testnet 6 merged PRs
  docs/changelog.rst
Labels: dev: Please Review

#2258 Fix travis mac deployment issue
  .travis.yml
  raiden.spec
Labels: dev: Please Review

#2261 Handle 404 on user presence check on matrix
  raiden/network/transport/matrix.py
Labels: dev: Please Review, matrix

#2265 Release 0.6
  .bumpversion_client.cfg
  docs/changelog.rst
  docs/conf.py
  requirements.txt
  setup.py
Labels: dev: Please Review

#2271 Bump gevent to 1.3.6
  requirements.txt
Labels: dev: Please Review

#2248 unskip test_insufficient_funds
  raiden/tests/integration/test_pythonapi.py
Labels: dev: Please Review

#2273 Add changelog entry for 2264
  docs/changelog.rst
Labels: dev: Please Review

#2294 Fix cli tests after the addition of acknowledgement of disclaimer
  raiden/tests/integration/cli/test_cli.py
Labels: dev: Please Review

#2297 bugfix: handle_refundtransfer must forward send refund event
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#2299 bugfix #2293
  docs/changelog.rst
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/transfer/mediated_transfer/initiator.py
Labels: dev: Please Review

#2314 Fix skip test
  raiden/tests/integration/transfer/test_mediatedtransfer.py
Labels: dev: Please Review

#2317 Add raiden-debug.logs to .gitignore
  .gitignore
Labels: dev: Please Review

#2320 tests: wait_assert with function as the first argument
  raiden/tests/integration/transfer/test_mediatedtransfer.py
  raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
  raiden/tests/utils/transfer.py
Labels: dev: Please Review

#2308 Add webui support for switching token input between decimal and integer values
  docs/changelog.rst
  raiden/ui/web/src/app/app.module.ts
  raiden/ui/web/src/app/components/channel-table/channel-table.component.spec.ts
  raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
  raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.html
  raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.spec.ts
  raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.ts
  raiden/ui/web/src/app/components/join-dialog/join-dialog.component.html
  raiden/ui/web/src/app/components/join-dialog/join-dialog.component.spec.ts
  raiden/ui/web/src/app/components/join-dialog/join-dialog.component.ts
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.spec.ts
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.html
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.spec.ts
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.ts
  raiden/ui/web/src/app/components/token-events/token-events.component.ts
  raiden/ui/web/src/app/components/token-input/token-input.component.css
  raiden/ui/web/src/app/components/token-input/token-input.component.html
  raiden/ui/web/src/app/components/token-input/token-input.component.spec.ts
  raiden/ui/web/src/app/components/token-input/token-input.component.ts
  raiden/ui/web/src/app/modules/material-components/material-components.module.ts
  raiden/ui/web/src/app/services/raiden.config.ts
  raiden/ui/web/src/app/services/raiden.service.ts
  raiden/ui/web/src/main.ts
  raiden/ui/web/tslint.json
Labels: dev: Please Review

#2326 User superclass __eq__ for inheriting statechanges and events
  raiden/transfer/architecture.py
  raiden/transfer/events.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/state_change.py
Labels: dev: Please Review

#2330 Remove unused deploy script code
  tools/deploy.py
Labels: dev: Please Review

#2323 updating glossary
  docs/glossary.rst
Labels: dev: Please Review

#2327 Removed unused flag leave_channels
  raiden/app.py
  raiden/raiden_service.py
  raiden/tests/utils/tests.py
  raiden/ui/cli.py
Labels: dev: Please Review
