Repository raiden-network/raiden, pull requests merged in 2018-10, with the labels that each got.

#2644 Add join-network task
  tools/scenario-player/example-scenarios/scenario-basic.yaml
  tools/scenario-player/scenario_player/tasks/token_network.py
Labels: dev: Please Review

#2645 Reenable automated PyPI uploading
  .travis.yml
Labels: dev: Please Review

#2648 Fix typo in developer install instructions
  docs/overview_and_guide.rst
Labels: dev: Please Review

#2616 Open channel scenario added
  raiden/tests/scenarios/open-channel-different-scenarios.yaml
  tools/scenario-player/scenario_player/tasks/channels.py
Labels: dev: Please Review

#2653 Update starting disclaimer with a privacy notice
  raiden/ui/cli.py
Labels: dev: Please Review

#2646 All scenarios to fund and top up a channel
  raiden/tests/scenarios/funding-channel-scenarios.yaml
Labels: dev: Please Review

#2656 Default to fast gas price in case no settings are given
  tools/scenario-player/scenario_player/runner.py
Labels: dev: Please Review

#2657 [SP] Allow processing 204 responses
  tools/scenario-player/scenario_player/tasks/raiden_api.py
Labels: dev: Please Review

#2660 Add a note in contributing.md about updating docs/specs
  CONTRIBUTING.md
Labels: dev: Please Review

#2666 pylint: fixed warning for inherited _run
  raiden/raiden_service.py
Labels: dev: Please Review

#2667 Update synapse binary test server
  .travis.yml
  tools/install_synapse.sh
Labels: dev: Please Review, matrix, testing

#2670 Increase the reveal timeout
  raiden/settings.py
Labels: dev: Please Review

#2673 Give positive examples in the CONTRIBUTING guide
  CONTRIBUTING.md
Labels: dev: Please Review

#2674 updatd the contributing guide
  CONTRIBUTING.md
Labels: dev: Please Review

#2681 [SP] Allow arbitrary address input in the `to` field of tasks
  tools/scenario-player/example-scenarios/scenario-basic.yaml
  tools/scenario-player/scenario_player/tasks/channels.py
Labels: dev: Please Review

#2678 Add note on connect and initial_channel_target
  docs/rest_api.rst
Labels: dev: Please Review

#2688 Contributing update
  CONTRIBUTING.md
Labels: dev: Please Review

#2696 Add changelog entry for 2568
  docs/changelog.rst
Labels: dev: Please Review

#2693 mention the usage of WETH in the docs
  docs/api_walkthrough.rst
  docs/rest_api.rst
Labels: dev: Please Review

#2611 Mediated transfers scenario
  raiden/tests/scenarios/mediated-transfers-scnenarios.yaml
Labels: dev: Please Review

#2712 Added protocol version to the Ping message
  raiden/constants.py
  raiden/encoding/messages.py
  raiden/messages.py
  raiden/network/transport/udp/udp_transport.py
  raiden/tests/integration/test_service.py
  raiden/tests/unit/test_binary_encoding.py
  raiden/tests/unit/test_messages.py
  raiden/utils/typing.py
Labels: dev: Please Review

#2717 Added changelog protocol version in Ping
  docs/changelog.rst
Labels: dev: Please Review

#2718 techical -> technical [skip ci]
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: dev: Please Review

#2724 Fix API docs for unencoded hexaddress arguments
  docs/rest_api.rst
Labels: dev: Please Review

#2727 removed unused get_transaction_from [skip ci]
  raiden/network/rpc/client.py
Labels: dev: Please Review

#2694 Pointing to the raiden contracts repos
  README.rst
Labels: dev: Please Review

#2722 Explicit check for queue length in inplace_delete_message_queue
  raiden/transfer/node.py
Labels: dev: Please Review

#2736 bugfix: libraries could be None
  raiden/network/rpc/client.py
Labels: dev: Please Review

#2735 tests: removed pending_mediated_transfer
  raiden/raiden_service.py
  raiden/tests/integration/test_integration_events.py
  raiden/tests/integration/test_settlement.py
  raiden/tests/utils/protocol.py
  raiden/tests/utils/transfer.py
Labels: dev: Please Review

#2732 Avoid refreshing tokens balances on every tokens refresh
  raiden/ui/web/src/app/components/token-network-selector/token-network-selector.component.ts
  raiden/ui/web/src/app/components/token-network/token-network.component.ts
  raiden/ui/web/src/app/services/raiden.service.ts
Labels: dev: Please Review, ui

#2748 Resolve mixup in runner naming
  raiden/ui/runners.py
Labels: dev: Please Review

#2738 Remove tester blockchain from the tests
  .travis.yml
  raiden/tests/fixtures/variables.py
  raiden/tests/integration/fixtures/blockchain.py
  raiden/tests/integration/long_running/test_token_networks.py
  raiden/tests/integration/rpc/test_assumptions.py
  raiden/tests/utils/tester.py
Labels: dev: Please Review

#2742 fix formatting error
  docs/rest_api.rst
Labels: dev: Please Review

#2754 Fix bug at _initialize_queues
  raiden/raiden_service.py
Labels: dev: Please Review

#2759 Fix logging if node runs with matrix
  raiden/ui/runners.py
Labels: dev: Please Review

#2760 Document Internal server error(500) response
  docs/rest_api.rst
Labels: dev: Please Review

#2757 Added MessageHandler class
  raiden/app.py
  raiden/message_handler.py
  raiden/network/transport/matrix.py
  raiden/network/transport/udp/udp_transport.py
  raiden/raiden_service.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/integration/test_settlement.py
  raiden/tests/integration/test_stress.py
  raiden/tests/utils/network.py
  raiden/tests/utils/transfer.py
  raiden/ui/app.py
Labels: dev: Please Review

#2659 initial mixed scenario for one hop payments
  raiden/tests/scenarios/direct_transfers_happy_cases_1-1000_txs.yaml
  raiden/tests/scenarios/direct_transfers_mixed_edge_cases.yaml
  raiden/tests/scenarios/direct_transfers_stopped_node_scenarios.yaml
Labels: dev: Please Review

#2767 Scenario player v2
  tools/scenario-player/example-scenarios/scenario-example-v2.yaml
  tools/scenario-player/requirements.txt
  tools/scenario-player/scenario_player/__main__.py
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/base.py
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/tasks/execution.py
  tools/scenario-player/scenario_player/tasks/raiden_api.py
  tools/scenario-player/scenario_player/tasks/raiden_node.py
  tools/scenario-player/scenario_player/ui.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review, scenario player

#2751 Add basic test for routing
  raiden/tests/unit/test_tokennetwork.py
Labels: dev: Please Review

#2770 changes to constants
  raiden/constants.py
  raiden/tests/integration/test_endpointregistry.py
  raiden/ui/sync.py
  raiden/utils/gas_reserve.py
  tools/gas_cost_measures.py
Labels: dev: Please Review

#2768 Fix homebrew update ssh key permissions
  .travis/update_formula.sh
Labels: dev: Please Review

#2775 Remove invalid check for onchain secret registration
  raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
  raiden/transfer/channel.py
Labels: dev: Please Review

#2762 Prioritize routes which have funds for refunds
  raiden/routing.py
  raiden/tests/unit/test_tokennetwork.py
Labels: dev: Please Review

#2783 Small docs fixes
  docs/rest_api.rst
Labels: dev: Please Review

#2781 CM: Added node address in the logs
  raiden/connection_manager.py
Labels: dev: Please Review

#2782 transaction queue reinit in a separate func
  raiden/raiden_service.py
Labels: dev: Please Review

#2787 bugfix: InitChain must use deployed blocknumber
  raiden/raiden_service.py
Labels: dev: Please Review

#2790 Remove last references to eth-tester
  raiden/constants.py
  raiden/tests/conftest.py
  raiden/utils/__init__.py
Labels: dev: Please Review

#2789 Issue 2785
  raiden/network/transport/udp/healthcheck.py
  raiden/network/transport/udp/udp_transport.py
  raiden/raiden_service.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_stress.py
  raiden/tests/unit/test_udp_transport.py
  raiden/tests/utils/network.py
  raiden/ui/app.py
Labels: dev: Please Review

#2774 Add a documentation section for copyright attributions
  docs/index.rst
  docs/trademarks.rst
Labels: dev: Please Review

#2800 Fix node funding, add assert_sum task
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/base.py
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/tasks/raiden_api.py
Labels: dev: Please Review

#2799 Fix RaidenService typos
  raiden/raiden_service.py
Labels: dev: Please Review

#2803 note about switching ethereum clients
  docs/overview_and_guide.rst
Labels: dev: Please Review

#2810 stress test remove operation timeouts
  raiden/tests/integration/test_stress.py
Labels: dev: Please Review

#2822 added changelog for 2813 [skip ci]
  docs/changelog.rst
Labels: dev: Please Review

#2825 changelog for poll confirmation
  docs/changelog.rst
Labels: dev: Please Review

#2816 Update webui documentation and screenshot
  docs/images/raiden_webui_channels_page_screenshot.png
  docs/images/raiden_webui_landing_page_screenshot.png
  docs/images/raiden_webui_tokens_page_screenshot.png
  docs/images/raiden_webui_wallet_page_screenshot.png
  docs/webui_tutorial.rst
Labels: dev: Please Review

#2830 update cli disclaimer
  raiden/ui/cli.py
Labels: dev: Please Review

#2837 Temporarily skip version check
  raiden/utils/__init__.py
Labels: dev: Please Review

#2833 Fix homebrew formula updating
  .travis/update_formula.sh
Labels: dev: Please Review

#2831 Some SP improvements
  tools/scenario-player/example-scenarios/scenario-example-v2.yaml
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review, scenario player

#2839 Fix cli tests for new disclaimer
  raiden/tests/integration/cli/test_cli.py
Labels: dev: Please Review

#2847 Fix typing ChainMap -> ChannelMap
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#2844 Fixed a attribute that was renamed
  raiden/network/proxies/token.py
  tools/transfer_eth.py
Labels: dev: Please Review

#2683 [skip ci] add note about concurrency for join and leave
  docs/rest_api.rst
Labels: dev: Please Review

#2848 removed test_lock_expiry timming dependencies
  raiden/tests/integration/test_settlement.py
  raiden/tests/utils/protocol.py
Labels: dev: Please Review

#2850 Remove unneeded CI stage
  .travis.yml
Labels: dev: Please Review

#2851 Fix wrong arg name in handle_contract_send_secretreveal
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#2854 Add information about the commit labels to the Contributing guide
  CONTRIBUTING.md
Labels: dev: Please Review

#2861 Fixed a param option
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
Labels: dev: Please Review

#2855 removed unused test util [skip ci]
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
Labels: dev: Please Review

#2826 Scenarios dominik
  raiden/tests/scenarios/Scenario-Kill-Receiver.yaml
  raiden/tests/scenarios/Scenario-Mediated-Transfer-in-Hexagon.yaml
  raiden/tests/scenarios/Scenario-Re-Routing.yaml
  raiden/tests/scenarios/ci/Scenario-Stress-Hub.yaml
Labels: dev: Please Review

#2867 add note about echo node not being available on mainnet
  docs/api_walkthrough.rst
Labels: dev: Please Review

#2865 Make testnets optional in guide, remove bootnodes
  docs/overview_and_guide.rst
Labels: dev: Please Review

#2863 tests: using must_contain_entry
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
Labels: dev: Please Review

#2853 Report problematic versions at contract version mismatch
  raiden/network/proxies/discovery.py
  raiden/network/proxies/secret_registry.py
  raiden/network/proxies/token_network.py
  raiden/network/proxies/token_network_registry.py
  raiden/network/proxies/utils.py
  raiden/ui/app.py
  raiden/utils/__init__.py
Labels: dev: Please Review

#2872 Small docs improvements [skip ci]
  docs/overview_and_guide.rst
Labels: dev: Please Review

#2875 tests: removed duplicated test
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
Labels: dev: Please Review

#2871 Properly recognize environment type from cli
  raiden/tests/integration/cli/test_cli.py
  raiden/ui/app.py
  raiden/ui/cli.py
  raiden/utils/cli.py
Labels: dev: Please Review

#2880 Improve startup time, record node's stdout / stderr
  raiden/ui/app.py
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/base.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review, scenario player

#2876 Remove the 'What is the developer preview' from docs
  docs/index.rst
  docs/what_is_the_dev_preview.rst
Labels: dev: Please Review

#2882 Switch default network_id to mainnet
  raiden/ui/cli.py
Labels: dev: Please Review

#2877 tests: cron job always runs integration tests
  .travis.yml
Labels: dev: Please Review

#2864 Long path scenario
  raiden/tests/scenarios/ci/long_path_mediated_transfers.yaml
Labels: dev: Please Review

#2904 Fix synapse build on Travis
  tools/install_synapse.sh
Labels: dev: Please Review, matrix

#2891 Fixed type annotations
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/secret_registry.py
Labels: dev: Please Review

#2892 Improved logging for failed unlock
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#2898 Add time to debug log file
  raiden/log_config.py
Labels: dev: Please Review

#2900 bugfix: Fix --showconfig
  raiden/ui/config.py
Labels: dev: Please Review

#2897 Bug report checklist
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: dev: Please Review

#2903 Document the reason balance hash is serialized in ContractSendChannelClose
  raiden/transfer/events.py
Labels: dev: Please Review

#2902 Fixed log message
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review

#2912 Force node to v10 on macOS builds
  .travis/prepare_os_osx.sh
Labels: dev: Please Review

#2914 Fix flaky test_batch_unlock
  raiden/tests/fixtures/variables.py
Labels: dev: Please Review

#2917 Fix Travis webui building again
  .travis/prepare_os_osx.sh
  setup.py
Labels: dev: Please Review

#2920 Log system spec on startup
  raiden/ui/runners.py
Labels: dev: Please Review

#2926 Add a log of the eth client version at start
  raiden/network/rpc/client.py
Labels: dev: Please Review

#2928 Allow specifying node api address
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/tasks/channels.py
Labels: dev: Please Review, scenario player

#2927 Move issue checklist to commented out section
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: dev: Please Review

#2930 fix note boxes
  docs/rest_api.rst
Labels: dev: Please Review

#2942 Fix address handling after #2928
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
Labels: dev: Please Review, scenario player
