Repository raiden-network/raiden, pull requests merged in 2018-11, with the labels that each got.

#2949 Add a changelog entry for 2933
  docs/changelog.rst
Labels: dev: Please Review

#2929 Add log_time to state changes
  raiden/storage/sqlite.py
  raiden/storage/utils.py
  raiden/storage/wal.py
  raiden/tests/unit/test_wal.py
Labels: dev: Please Review

#2954 reworded changelog
  docs/changelog.rst
Labels: dev: Please Review

#2958 Increase DB version for PR #2929
  raiden/storage/sqlite.py
Labels: dev: Please Review

#2944 Added synchronization to the WAL
  raiden/storage/wal.py
Labels: dev: Please Review

#2961 Fix typo in the changelog
  docs/changelog.rst
Labels: dev: Please Review

#2937 Switch the issue checklist to an actual checklist.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: dev: Please Review

#2965 update payment return objects [skip ci]
  docs/api_walkthrough.rst
  docs/rest_api.rst
Labels: dev: Please Review

#2966 Don't show full block info in info message.
  raiden/tasks.py
Labels: dev: Please Review

#2967 ActionInitChain dispatch through handle_state_change
  raiden/raiden_service.py
Labels: dev: Please Review

#2945 Use JSON as a default logging format
  raiden/log_config.py
Labels: dev: Please Review

#2970 Add changelog entry for 2921
  docs/changelog.rst
Labels: dev: Please Review

#2971 Update requests to v2.20.0 to fix security vulnerability
  constraints.txt
Labels: dev: Please Review

#2972 Remove outdated smart contract docs
  docs/index.rst
  docs/smart_contracts.rst
Labels: dev: Please Review

#2979 Adjust config_sample.toml after contract argument changes
  config_sample.toml
Labels: dev: Please Review

#2980 Remove code related to channel withdraw
  raiden/blockchain/events.py
  raiden/blockchain_events_handler.py
  raiden/exceptions.py
  raiden/network/proxies/token_network.py
  raiden/tests/integration/contracts/test_token_network.py
Labels: dev: Please Review

#2982 Convert QueueId keys to string before logging
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#2983 Fix fallout from #2884
  raiden/tasks.py
Labels: dev: Please Review

#2986 Handle transaction execution error for parity
  raiden/network/rpc/smartcontract_proxy.py
Labels: dev: Please Review

#2992 Remove unused state machine code and view function
  raiden/transfer/node.py
  raiden/transfer/views.py
Labels: dev: Please Review

#3002 [SP] Properly handle 0 for 'initial_channel_target'
  tools/scenario-player/scenario_player/tasks/token_network.py
Labels: dev: Please Review, scenario player

#3019 docs: geth --fast is now called "--syncmode fast"
  docs/overview_and_guide.rst
Labels: dev: Please Review, documentation

#3026 Fix handle_cancelpayment
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/transfer/mediated_transfer/initiator_manager.py
Labels: dev: Please Review

#3037 [SP] Fix send_transaction gaslimit argument
  tools/scenario-player/scenario_player/node_support.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/base.py
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review, scenario player

#3032 Save time and version in sqlite on startup
  raiden/storage/sqlite.py
  raiden/tests/unit/test_sqlitestorage.py
  raiden/tests/unit/test_wal.py
Labels: dev: Please Review

#3043 At _log_raiden_run handle None version
  raiden/utils/__init__.py
Labels: dev: Please Review

#3042 Pytest new version
  constraints.txt
Labels: dev: Please Review

#3055 Enforce proper development setup
  raiden/ui/runners.py
  raiden/utils/__init__.py
Labels: dev: Please Review

#3060 Fix inconsistent class name usage
  raiden/transfer/mediated_transfer/events.py
Labels: dev: Please Review

#3062 Misc mypy type checking fixes
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/mediated_transfer/state_change.py
  raiden/utils/serialization.py
Labels: dev: Please Review

#3050 Clear unused exception from except
  raiden/raiden_service.py
Labels: dev: Please Review

#3076 Add a section on testing to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: dev: Please Review, documentation

#3029 Nightly coveralls
  .travis.yml
  .travis/coverage.sh
  .travis/install.sh
  .travis/run.sh
Labels: dev: Please Review

#3087 Explain which queues are cleared with Delivered/Processed
  docs/onboarding.rst
  raiden/transfer/node.py
Labels: dev: Please Review

#3100 Circle CI composed all integration tests into a single job
  .circleci/config.yml
  docs/onboarding.rst
Labels: dev: Please Review, infrastructure
