Repository raiden-network/raiden, pull requests merged in 2018-09, with the labels that each got.

#2333 Add 2170 to changelog
  docs/changelog.rst
Labels: dev: Please Review

#2348 Fix automatic deployment again
  .travis.yml
  .travis/update_formula.sh
Labels: dev: Please Review

#2312 Add EIP55 address validation to dialogs
  docs/changelog.rst
  raiden/ui/web/src/app/app.module.ts
  raiden/ui/web/src/app/components/address-input/address-input.component.css
  raiden/ui/web/src/app/components/address-input/address-input.component.html
  raiden/ui/web/src/app/components/address-input/address-input.component.spec.ts
  raiden/ui/web/src/app/components/address-input/address-input.component.ts
  raiden/ui/web/src/app/components/channel-table/channel-table.component.spec.ts
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.spec.ts
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.html
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.spec.ts
  raiden/ui/web/src/app/components/register-dialog/register-dialog.component.html
  raiden/ui/web/src/app/components/register-dialog/register-dialog.component.spec.ts
  raiden/ui/web/src/app/components/register-dialog/register-dialog.component.ts
  raiden/ui/web/src/app/services/raiden.service.ts
Labels: dev: Please Review

#2342 clear empty queues
  raiden/transfer/node.py
Labels: dev: Please Review

#2337 NotifyingQueue must start set if it has items
  raiden/network/transport/udp/udp_transport.py
  raiden/tests/unit/test_notifyingqueue.py
  raiden/utils/notifying_queue.py
Labels: dev: Please Review

#2354 Handle missing values for gevent.signal callback
  raiden/ui/cli.py
Labels: dev: Please Review

#2344 restapi: check the Raiden service is running
  raiden/api/rest.py
Labels: dev: Please Review

#2346 travis: always show the current checkout commit
  .travis.yml
Labels: dev: Please Review

#2328 Added secrethash to easy debugging
  raiden/transfer/mediated_transfer/events.py
Labels: dev: Please Review

#2355 lint: no-member is usually an error
  Makefile
  raiden/raiden_service.py
  raiden/settings.py
  raiden/tests/conftest.py
  raiden/tests/fixtures/variables.py
  raiden/tests/utils/smoketest.py
  raiden/utils/solc.py
Labels: dev: Please Review

#2352 Fix two instances of uncaught exceptions in the Rest API
  raiden/api/rest.py
Labels: dev: Please Review

#2357 Follow up to PR #1990
  tools/gas_cost_measures.py
Labels: dev: Please Review

#2377 bugfix: global queue was not being cleared
  raiden/tests/unit/test_node_queue.py
  raiden/transfer/node.py
Labels: dev: Please Review

#2371 Remove flake8-coding module
  requirements-lint.txt
  setup.cfg
Labels: dev: Please Review

#2378 Fix vulnerable ansible requirements
  tools/ansible/requirements.txt
Labels: dev: Please Review

#2368 Changelog entry for 2356
  docs/changelog.rst
Labels: dev: Please Review

#2380 Changelog entry for 862
  docs/changelog.rst
Labels: dev: Please Review

#2389 increase frequency of snapshotting
  raiden/constants.py
  raiden/raiden_service.py
  raiden/storage/sqlite.py
Labels: dev: Please Review

#2349 Nightly releases
  .travis.yml
  .travis/prepare_os_osx.sh
  .travis/set_tag.sh
  .travis/update_formula.sh
  Makefile
  docker/build.Dockerfile
  raiden/log_config.py
  raiden/tests/utils/events.py
  requirements-dev.txt
  requirements.txt
Labels: dev: Please Review

#2400 test utils required web3 4.6.0
  requirements-dev.txt
Labels: dev: Please Review

#2416 Fix for #2408
  raiden/blockchain/state.py
  raiden/network/proxies/payment_channel.py
Labels: dev: Please Review

#2403 bugfix: transport can be used during shutdown
  raiden/network/transport/udp/udp_transport.py
Labels: dev: Please Review

#2405 Added RaidenEventHandler class
  raiden/app.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/utils/network.py
  raiden/ui/cli.py
  tools/scenario_runner.py
Labels: dev: Please Review

#2415 removed unused function
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#2398 Add note on Infura and WebUI
  docs/webui_tutorial.rst
Labels: dev: Please Review

#2420 The transport layer should not know about events
  raiden/network/transport/matrix.py
  raiden/network/transport/udp/udp_transport.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2424 Pylintrc
  .pylint.rc
  Makefile
Labels: dev: Please Review

#2434 Docs for markers
  raiden/transfer/architecture.py
Labels: dev: Please Review, documentation

#2406 moved matrix test to the integration folder
  raiden/tests/integration/test_matrix_transport.py
Labels: dev: Please Review

#2433 Renamed SendRevealSecret -> SendSecretReveal
  docs/rest_api.rst
  raiden/messages.py
  raiden/raiden_event_handler.py
  raiden/tests/integration/test_regression.py
  raiden/tests/integration/transfer/test_mediatedtransfer_events.py
  raiden/tests/unit/test_node_queue.py
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/state.py
  raiden/transfer/mediated_transfer/target.py
Labels: :warning: Breaking change, dev: Please Review

#2442 Upgrade pylint to work with python 3.7, isort skip
  Makefile
  requirements-lint.txt
Labels: dev: Please Review

#2438 Add changelog entry for 2419
  docs/changelog.rst
Labels: dev: Please Review

#2443 Increment DB version after #2399
  raiden/storage/sqlite.py
Labels: dev: Please Review

#2446 raise port in use earlier
  raiden/api/rest.py
Labels: dev: Please Review

#2452 Add missing comma
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#2448 Add different issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/critical_vulnerability_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: dev: Please Review

#2376 Improves functionality of token amount input
  docs/changelog.rst
  raiden/ui/web/src/app/app.module.ts
  raiden/ui/web/src/app/components/channel-table/channel-table.component.spec.ts
  raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.html
  raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.spec.ts
  raiden/ui/web/src/app/components/deposit-dialog/deposit-dialog.component.ts
  raiden/ui/web/src/app/components/join-dialog/join-dialog.component.html
  raiden/ui/web/src/app/components/join-dialog/join-dialog.component.spec.ts
  raiden/ui/web/src/app/components/join-dialog/join-dialog.component.ts
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.spec.ts
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.html
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.spec.ts
  raiden/ui/web/src/app/components/payment-dialog/payment-dialog.component.ts
  raiden/ui/web/src/app/components/token-input/token-input.component.html
  raiden/ui/web/src/app/components/token-input/token-input.component.spec.ts
  raiden/ui/web/src/app/components/token-input/token-input.component.ts
  raiden/ui/web/src/app/directives/allowed-decimals.directive.spec.ts
  raiden/ui/web/src/app/directives/allowed-decimals.directive.ts
Labels: dev: Please Review

#2457 Add changelog for #2451
  docs/changelog.rst
Labels: dev: Please Review

#2456 Improve logging at channel creation
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#2423 Remove wrong debug endpoint from docs
  docs/rest_api.rst
Labels: dev: Please Review

#2365 Port in use message
  raiden/ui/cli.py
Labels: dev: Please Review

#2472 Remove send queued from transports start and to service
  raiden/messages.py
  raiden/network/transport/matrix.py
  raiden/network/transport/udp/udp_transport.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2473 Use our special patched pystun package
  requirements.txt
Labels: dev: Please Review

#2463 Add typing for payment identifier in the transfer call chain
  raiden/api/python.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2474 Start transport before alarm.first_run
  raiden/messages.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2477 Replace constants.NULL_HASH_BYTES with EMPTY_HASH
  raiden/constants.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2469 pinned dependencies
  .travis/install.sh
  constraints.txt
  docs/changelog.rst
  docs/macos_install_guide.rst
  docs/overview_and_guide.rst
  requirements.txt
  setup.py
Labels: dev: Please Review

#2478 Update gas costs after contracts update
  raiden/constants.py
Labels: dev: Please Review

#2479 Fix changelog for pinned versions
  docs/changelog.rst
Labels: dev: Please Review

#2476 Add payment history to the webui.
  docs/changelog.rst
  raiden/ui/web/src/app/app.component.ts
  raiden/ui/web/src/app/app.module.ts
  raiden/ui/web/src/app/components/channel-table/channel-table.component.html
  raiden/ui/web/src/app/components/payment-history/payment-history.component.css
  raiden/ui/web/src/app/components/payment-history/payment-history.component.html
  raiden/ui/web/src/app/components/payment-history/payment-history.component.spec.ts
  raiden/ui/web/src/app/components/payment-history/payment-history.component.ts
  raiden/ui/web/src/app/models/payment-event.ts
  raiden/ui/web/src/app/services/raiden.service.spec.ts
  raiden/ui/web/src/app/services/raiden.service.ts
Labels: dev: Please Review

#2488 Fix automatic homebrew formula updating
  .travis/update_formula.sh
Labels: dev: Please Review

#2490 Fix handle_request_parsing_error
  raiden/api/rest.py
Labels: dev: Please Review

#2493 Adds correct default value to --rpccorsdomain to the web_ui tutorial.
  docs/webui_tutorial.rst
Labels: dev: Please Review

#2487 For payment received events filter for the initiator
  docs/changelog.rst
  raiden/api/python.py
  raiden/tests/integration/api/test_restapi.py
Labels: dev: Please Review

#2500 Handled exceptions
  raiden/api/rest.py
  raiden/connection_manager.py
Labels: dev: Please Review

#2506 Fix internal events endpoint
  raiden/api/v1/resources.py
Labels: dev: Please Review

#2508 Bump raiden contracts to 0.3.1
  constraints.txt
Labels: dev: Please Review

#2511 Add locksroot and locked_amount to participant details
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#2514 Skip stress test due to being flaky
  raiden/tests/integration/test_stress.py
Labels: dev: Please Review

#2480 ui: lowered lockfile logging level
  raiden/log_config.py
  raiden/ui/cli.py
Labels: dev: Please Review

#2481 ui: reduced default verbosity of the transport
  raiden/network/transport/matrix.py
Labels: dev: Please Review

#2525 Cache gas price calculations
  raiden/network/rpc/client.py
Labels: dev: Please Review

#2528 Add descending order by block_number as default for blockchain events on webui.
  docs/changelog.rst
  raiden/ui/web/src/app/components/event-list/event-list.component.html
Labels: dev: Please Review

#2531 Expose default settle and reveal timeouts in webui's config*.json
  raiden/api/rest.py
  raiden/ui/web/src/app/services/raiden.config.ts
Labels: dev: Please Review, ui

#2538 Increase the time a notification stays visible on the webui
  docs/changelog.rst
  raiden/ui/web/src/app/app.module.ts
Labels: dev: Please Review

#2533 Adds validation for settle timeout against reveal timeout when opening a channel from the webui
  docs/changelog.rst
  raiden/ui/web/src/app/components/channel-table/channel-table.component.ts
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.html
  raiden/ui/web/src/app/components/open-dialog/open-dialog.component.ts
  raiden/ui/web/src/assets/config/config.development.json
  raiden/ui/web/src/assets/config/config.production.json
Labels: dev: Please Review

#2539 If onchain balance hash is empty don't search the WAL
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#2540 Skip stress test again
  raiden/tests/integration/test_stress.py
Labels: dev: Please Review

#2541 Gray out token registration functionality in the WebUI
  raiden/ui/web/src/app/components/token-network/token-network.component.html
  raiden/ui/web/src/app/components/token-network/token-network.component.spec.ts
  raiden/ui/web/src/app/components/token-network/token-network.component.ts
  raiden/ui/web/src/app/services/network-type.enum.ts
  raiden/ui/web/src/app/services/raiden.config.ts
  raiden/ui/web/src/app/services/raiden.service.ts
  raiden/ui/web/src/assets/config/config.development.json
  raiden/ui/web/src/assets/config/config.production.json
Labels: dev: Please Review

#2527 Leave and clean unused/old/non-relevant participating rooms
  raiden/network/transport/matrix.py
Labels: dev: Please Review, matrix

#2546 Fix homebrew formula updating
  .travis/update_formula.sh
Labels: dev: Please Review

#2544 If our balance hash is empty don't query events for our BP
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#2552 pylint enabled bad-except-order
  .pylint.rc
  raiden/connection_manager.py
Labels: dev: Please Review

#2555 Fix homebrew formula updating. Again.
  .travis/update_formula.sh
Labels: dev: Please Review

#2551 simplified configure_logging
  raiden/log_config.py
Labels: dev: Please Review

#2573 removed unused ansible files
  tools/ansible/99-tcp-timewait.conf
  tools/ansible/README.md
  tools/ansible/ansible.cfg
  tools/ansible/build-ami-cpython.yaml
  tools/ansible/build-ami-pypy.yaml
  tools/ansible/contrib/inventory/ec2.ini
  tools/ansible/contrib/inventory/ec2.py
  tools/ansible/contrib/inventory/inventory
  tools/ansible/group_vars/key_raiden.yaml
  tools/ansible/group_vars/tag_Name_Build.yaml
  tools/ansible/group_vars/tag_Name_Scenario.yaml
  tools/ansible/prepare-scenario.yaml
  tools/ansible/raiden_requirements.patch
  tools/ansible/requirements.txt
  tools/ansible/roles/build-ami/meta/main.yaml
  tools/ansible/roles/build-ami/vars/main.yaml
  tools/ansible/roles/common/tasks/scenario_ami_id_from_name.yaml
  tools/ansible/roles/common/vars/main.yaml
  tools/ansible/roles/scenario/tasks/read_scenario_params.yaml
  tools/ansible/roles/scenario/tasks/terminate.yaml
  tools/ansible/roles/scenario/vars/main.yaml
  tools/ansible/run-scenario.yaml
  tools/ansible/serpent_setup.patch
Labels: dev: Please Review

#2491 travis: opt-out for the integration tests
  .travis.yml
Labels: dev: Please Review, needs discussion

#2576 Simplified the filter polling
  raiden/blockchain/events.py
  raiden/network/proxies/secret_registry.py
  raiden/network/proxies/token_network.py
  raiden/network/proxies/token_network_registry.py
  raiden/network/rpc/client.py
  raiden/raiden_service.py
  raiden/utils/filters.py
Labels: dev: Please Review

#2575 Clarified lock usage in Raiden service
  raiden/raiden_service.py
  raiden/tests/fixtures/variables.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
Labels: dev: Please Review

#2577 Improvements for the new block logging message
  raiden/tasks.py
Labels: dev: Please Review

#2581 removed unused namedtuple
  raiden/blockchain/events.py
Labels: dev: Please Review

#2524 Scenario player
  raiden/log_config.py
  setup.cfg
  tools/scenario-player/README.rst
  tools/scenario-player/example-scenarios/scenario-basic.yaml
  tools/scenario-player/requirements.txt
  tools/scenario-player/scenario_player/__init__.py
  tools/scenario-player/scenario_player/__main__.py
  tools/scenario-player/scenario_player/exceptions.py
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks.py
  tools/scenario-player/scenario_player/utils.py
  tools/scenario.json
  tools/scenario_runner.py
  tools/testnet/files/dockerfiles/scenario_player/Dockerfile
Labels: dev: Please Review

#2580 Fixed netting event shortcuts
  raiden/blockchain/events.py
  raiden/tests/integration/test_integration_events.py
Labels: dev: Please Review

#2534 Scenario player improvements
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks.py
  tools/scenario-player/scenario_player/tasks/base.py
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/tasks/execution.py
  tools/scenario-player/scenario_player/tasks/raiden_api.py
  tools/scenario-player/scenario_player/tasks/raiden_node.py
Labels: dev: Please Review

#2595 Fix logging for 'Starting at...' message
  raiden/tasks.py
Labels: dev: Please Review

#2600 logging: logs before & after all transactions
  raiden/network/proxies/discovery.py
  raiden/network/proxies/secret_registry.py
  raiden/network/proxies/token.py
  raiden/network/proxies/token_network.py
  raiden/network/proxies/token_network_registry.py
Labels: dev: Please Review

#2601 [SP] Increase gas estimates for transactions
  tools/scenario-player/scenario_player/main.py
Labels: dev: Please Review

#2606 Update send-eth tool to use same conventions as scenario player
  tools/transfer_eth.py
Labels: dev: Please Review

#2612 Warn if older version DB files exist
  raiden/app.py
  raiden/storage/versions.py
Labels: dev: Please Review

#2609 Allow numeric network ids
  raiden/utils/cli.py
Labels: dev: Please Review

#2607 Handle matrix errors when inviting users
  raiden/network/transport/matrix.py
Labels: dev: Please Review, matrix

#2617 Fix crash on raiden startup
  raiden/app.py
Labels: dev: Please Review

#2589 Stress test compact logging
  raiden/log_config.py
  raiden/tests/conftest.py
  raiden/tests/integration/test_stress.py
Labels: dev: Please Review

#2596 Add basic scenarios to test channel closing
  raiden/tests/scenarios/close_channel_all_channels.yaml
  raiden/tests/scenarios/close_channel_one_channel.yaml
  raiden/tests/scenarios/close_channel_reopen_before_settle.yaml
Labels: dev: Please Review

#2610 logging StateChange/Event JSON encoded
  raiden/blockchain_events_handler.py
  raiden/network/transport/matrix.py
  raiden/network/transport/udp/udp_transport.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2614 flaky stress test
  raiden/network/rpc/client.py
  raiden/tests/integration/test_stress.py
Labels: dev: Please Review

#2625 Improve logging in send_raw_transaction
  raiden/network/rpc/client.py
  raiden/raiden_service.py
Labels: dev: Please Review

#2629 Add changelog entry for #2535
  docs/changelog.rst
Labels: dev: Please Review

#2627 fix test_stress when missing log-config
  raiden/tests/integration/test_stress.py
Labels: dev: Please Review

#2635 bugfix: redact was not returning the data
  raiden/raiden_service.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#2631 bugfix: rowcount doesn't work with select statements
  raiden/storage/sqlite.py
  raiden/tests/unit/test_wal.py
Labels: dev: Please Review

#2636 Add changelog for #2631
  docs/changelog.rst
Labels: dev: Please Review

#2624 reflect red eyes limits in docs
  docs/api_walkthrough.rst
  docs/rest_api.rst
Labels: dev: Please Review

#2634 simplified code
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review

#2637 removed outdated readme
  tools/README.md
Labels: dev: Please Review

#2639 Release v0.11.0
  .bumpversion_client.cfg
  docs/changelog.rst
  docs/conf.py
  setup.py
Labels: dev: Please Review

#2633 Removed unused code
  raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/state.py
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review
