Repository raiden-network/raiden, pull requests merged in 2019-02, with the labels that each got.

#3376 Generalized HoldOffChainSecretRequest to any event
  raiden/tests/utils/protocol.py
Labels: dev: Please Review

#3379 Gas reserve check was a no-op
  raiden/tasks.py
Labels: dev: Please Review

#3378 Increased sleep for wait until block
  raiden/network/blockchain_service.py
  raiden/tests/integration/api/test_pythonapi.py
  raiden/tests/integration/contracts/test_payment_channel.py
  raiden/tests/integration/contracts/test_token_network.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/long_running/test_token_networks.py
  raiden/tests/integration/test_service.py
  raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
  raiden/tests/utils/geth.py
Labels: dev: Please Review

#3381 Connection manager no longer attempts to deposit if per partner funds are zero
  docs/changelog.rst
  raiden/api/python.py
  raiden/connection_manager.py
  raiden/tests/integration/api/test_pythonapi.py
Labels: dev: Please Review

#3383 bugfix: flaky test_matrix_cross_server_with_load_balance
  raiden/tests/integration/test_matrix_transport.py
Labels: dev: Please Review

#3377 Removed duplicated tool to hold secret request
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/utils/protocol.py
Labels: dev: Please Review

#3404 Begin upgrade transaction
  raiden/utils/upgrades.py
Labels: dev: Please Review

#3408 typing: Added typing for static dispatch
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/target.py
  raiden/transfer/node.py
  raiden/transfer/token_network.py
  raiden/utils/typing.py
Labels: dev: Please Review

#3412 tests: simplified raidenapi test
  raiden/tests/integration/api/test_pythonapi.py
  raiden/tests/utils/events.py
Labels: dev: Please Review

#3415 remove unused fixture
  raiden/tests/integration/fixtures/blockchain.py
Labels: dev: Please Review

#3410 typing: Made TransitionResult state not optional
  raiden/transfer/architecture.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/target.py
  raiden/transfer/node.py
  raiden/utils/typing.py
Labels: dev: Please Review

#3421 Add cli flag to enable monitoring
  raiden/app.py
  raiden/raiden_event_handler.py
  raiden/ui/app.py
  raiden/ui/cli.py
Labels: dev: Please Review

#3424 Only check ethereum network id periodically
  raiden/network/blockchain_service.py
  raiden/tasks.py
  raiden/ui/runners.py
Labels: dev: Please Review

#3426 Fix scenario player for Python 3.7
  tools/debugging/json-log-to-html.py
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review

#3431 Add logging of REST-API results
  raiden/api/rest.py
Labels: dev: Please Review

#3437 Better name for shared serialization/deserialization class
  raiden/storage/serialize.py
  raiden/storage/sqlite.py
  raiden/utils/upgrades.py
Labels: dev: Please Review

#3441 Simplified event handling
  raiden/blockchain/events.py
  raiden/blockchain_events_handler.py
  raiden/exceptions.py
Labels: dev: Please Review

#3440 Removed broken util get_contract_path
  raiden/tests/utils/smartcontracts.py
  raiden/ui/console.py
  raiden/utils/__init__.py
  raiden/utils/smart_contracts.py
Labels: dev: Please Review

#3443 Change codecov config
  .codecov.yml
Labels: dev: Please Review, infrastructure

#3439 simplified test messages_out_of_order
  raiden/tests/integration/transfer/test_mediatedtransfer.py
  raiden/tests/utils/protocol.py
Labels: dev: Please Review

#3446 Better comment on the filelock usage
  raiden/raiden_service.py
Labels: dev: Please Review

#3449 Don't run migration if `old_db_filename` is None
  raiden/utils/upgrades.py
Labels: dev: Please Review

#3451 Join MS broadcast room when monitoring is enabled
  raiden/constants.py
  raiden/ui/app.py
Labels: dev: Please Review

#3453 Upgrade geth to v1.8.22 to test with Constantinople re-enabled
  .circleci/config.yml
  .travis.yml
  tools/testnet/files/dockerfiles/geth-testnet/Dockerfile
Labels: dev: Please Review

#3450 Add PFS info and checks at client start
  raiden/network/pathfinding.py
  raiden/tests/unit/test_pfs_integration.py
  raiden/ui/app.py
  raiden/ui/cli.py
Labels: dev: Please Review

#3474 enable pylint no-self-use
  .pylint.rc
  raiden/api/v1/encoding.py
  raiden/log_config.py
  raiden/network/transport/matrix/client.py
  raiden/network/transport/udp/udp_transport.py
  raiden/storage/serialize.py
  raiden/tests/unit/test_version_check.py
  raiden/tests/utils/mocks.py
  raiden/tests/utils/transport.py
  raiden/utils/upgrades.py
Labels: dev: Please Review

#3468 Simplfied and fixed the upgrade manager docstring
  raiden/utils/upgrades.py
Labels: dev: Please Review

#3470 Update raiden-contracts to 0.10.1
  constraints.txt
Labels: dev: Please Review

#3458 Add a simplified verification interface to RequestMonitoring
  raiden/messages.py
  raiden/tests/unit/test_messages.py
Labels: dev: Please Review

#3447 Feature: secret and/or hash with payment request
  docs/changelog.rst
  raiden/api/python.py
  raiden/api/rest.py
  raiden/api/v1/resources.py
  raiden/constants.py
  raiden/exceptions.py
  raiden/raiden_service.py
  raiden/tests/integration/api/test_restapi.py
Labels: dev: Please Review

#3484 Fix payment amount at payment status restoring during restart
  raiden/raiden_service.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/waiting.py
Labels: dev: Please Review

#3481 Use @staticmethod instead of disabling no-self-use
  raiden/api/v1/encoding.py
  raiden/message_handler.py
  raiden/network/transport/matrix/client.py
  raiden/raiden_event_handler.py
  raiden/tests/unit/test_version_check.py
  raiden/tests/utils/mocks.py
  raiden/tests/utils/transport.py
Labels: dev: Please Review

#3487 Fix scenario player Raiden node option handling
  tools/scenario-player/scenario_player/node_support.py
Labels: dev: Please Review

#3486 Removed useless lockstate_from_lock util
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/transfer/state.py
Labels: dev: Please Review

#3491 Added type information to raiden_service
  raiden/network/proxies/secret_registry.py
  raiden/raiden_service.py
Labels: dev: Please Review

#3494 Move "check interval" vars to constants.py
  raiden/constants.py
  raiden/tasks.py
Labels: dev: Please Review

#3482 Enable Arm binary build in CI
  .circleci/config.yml
  Makefile
  docker/build.Dockerfile
  raiden.spec
Labels: dev: Please Review, infrastructure

#3496 added type annotation to the message_handler.py
  raiden/message_handler.py
Labels: dev: Please Review

#3510 Geth: Moved logging to a separate folder
  .circleci/config.yml
  raiden/tests/integration/fixtures/blockchain.py
  raiden/tests/utils/geth.py
Labels: dev: Please Review

#3524 Fix smoketest stdout redirection
  raiden/tests/utils/smoketest.py
  raiden/ui/cli.py
Labels: dev: Please Review

#3523 Split make_signed_transfer() factory in two and fix test
  raiden/tests/integration/transfer/test_mediatedtransfer.py
  raiden/tests/unit/test_channelstate.py
  raiden/tests/unit/test_sqlite.py
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
  raiden/tests/utils/factories.py
Labels: dev: Please Review

#3502 Miscellaneous typing
  raiden/blockchain_events_handler.py
  raiden/message_handler.py
  raiden/messages.py
  raiden/storage/restore.py
  raiden/tasks.py
  raiden/transfer/mediated_transfer/state.py
Labels: dev: Please Review

#3532 Remove unused token network function
  raiden/transfer/token_network.py
Labels: dev: Please Review

#3533 Typing for the token network state machine
  raiden/transfer/node.py
  raiden/transfer/token_network.py
Labels: dev: Please Review

#3539 Update PFS request to post method
  raiden/routing.py
  raiden/tests/unit/test_pfs_integration.py
Labels: PFS, dev: Please Review

#3548 Fix test race condition
  raiden/raiden_service.py
Labels: dev: Please Review

#3536 Omit LATEST_XXX.txt from release artifacts when uploading to github
  .circleci/config.yml
Labels: dev: Please Review

#3538 Simplified some channel.py functions
  raiden/tests/unit/test_channelstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/target.py
  raiden/transfer/node.py
  raiden/transfer/token_network.py
Labels: dev: Please Review

#3541 Forbid self import
  .pylint.rc
  raiden/tests/utils/factories.py
Labels: dev: Please Review

#3551 Remove travis-ci
  .travis.yml
  .travis/before_install.sh
  .travis/coverage.sh
  .travis/download_geth.sh
  .travis/download_solc.sh
  .travis/install.sh
  .travis/prepare_os_linux.sh
  .travis/prepare_os_osx.sh
  .travis/run.sh
  .travis/run_smoketest.sh
Labels: dev: Please Review

#3557 Fix no-member complaint by pylint
  raiden/accounts.py
Labels: dev: Please Review

#3563 Added utility to run tests in parallel
  tools/parallel_tests.sh
Labels: dev: Please Review

#3561 Fix incorrect deployment build version
  .dockerignore
  .gitignore
  tools/testnet/.gitignore
Labels: dev: Please Review, infrastructure

#3571 Introduce CanonicalIdentifier
  raiden/messages.py
  raiden/network/proxies/token_network.py
  raiden/raiden_event_handler.py
  raiden/tests/unit/test_messages.py
  raiden/tests/utils/factories.py
  raiden/transfer/balance_proof.py
  raiden/transfer/channel.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/utils/__init__.py
Labels: dev: Please Review

#3573 Use CanonicalIdentifier in BalanceProofUnsignedState
  raiden/tests/unit/test_sqlite.py
  raiden/tests/utils/factories.py
  raiden/transfer/channel.py
  raiden/transfer/state.py
Labels: dev: Please Review
