Repository raiden-network/raiden, pull requests merged in 2019-04, with the labels that each got.

#3686 [SP] Add assert_ms_claim task, to check for MS claim events
  tools/scenario-player/example-scenarios/scenario-example-v2.yaml
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/blockchain.py
  tools/scenario-player/scenario_player/tasks/channels.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review

#3718 Re-apply fix from #3703
  tools/scenario-player/scenario_player/tasks/blockchain.py
  tools/scenario-player/scenario_player/utils.py
Labels: dev: Please Review

#3715 Remove unneeded comment. Better variable name
  raiden/network/proxies/token_network_registry.py
Labels: dev: Please Review

#3716 Remove eth-tester dependency
  constraints.txt
  requirements-dev.txt
Labels: dev: Please Review

#3657 simplified test for event transfer success
  raiden/tests/integration/test_echo_node.py
Labels: dev: Please Review

#3726 Fix spacing in service registry error message
  raiden/ui/app.py
Labels: dev: Please Review

#3719 Send PFS updates on own BP changes as well
  raiden/raiden_service.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/unit/test_version_check.py
  raiden/tests/unit/transfer/test_state_diff.py
  raiden/transfer/views.py
Labels: dev: Please Review

#3678 adding dir for adrs and testing adr doc
  docs/adr/0002-testing-strategy.md
  docs/adr/template.md
Labels: dev: Please Review

#3739 Upgrade isort to 4.3.16
  requirements-lint.txt
Labels: dev: Please Review

#3751 Skip echo node tests
  raiden/tests/integration/test_echo_node.py
Labels: dev: Please Review

#3755 Split out and pin constraints for dev dependencies
  .circleci/config.yml
  CONTRIBUTING.md
  Makefile
  constraints-dev.txt
  constraints.txt
  docs/macos_install_guide.rst
  docs/nix.rst
  docs/overview_and_guide.rst
  raiden/ui/cli.py
  setup.py
Labels: dev: Please Review

#3764 Add mediation fee to UpdatePFS message
  raiden/encoding/messages.py
  raiden/messages.py
Labels: dev: Please Review

#3770 fix #3663
  raiden/tests/utils/transfer.py
Labels: dev: Please Review

#3760 removed unecessary comment [skip tests]
  raiden/tests/integration/network/proxies/test_service_registry.py
Labels: dev: Please Review

#3763 get_random_service() should use the confirmed block
  raiden/network/pathfinding.py
  raiden/network/rpc/client.py
  raiden/tests/integration/network/proxies/test_service_registry.py
  raiden/tests/utils/smartcontracts.py
Labels: dev: Please Review

#3782 Remove unneeded comment
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#3783 Make gnureadline constraint platform specific
  constraints.txt
Labels: dev: Please Review

#3787 Adjust CLI transport arg comment on Matrix transport
  raiden/ui/cli.py
Labels: dev: Please Review

#3779 Fix tokennetwork -> payment network mapping migration
  raiden/storage/migrations/v20_to_v21.py
  raiden/tests/unit/storage/migrations/test_v20_to_v21.py
Labels: dev: Please Review

#3802 Using deployed block number
  raiden/ui/app.py
Labels: dev: Please Review

#3803 Fix message to PFS
  raiden/network/pathfinding.py
  raiden/tests/unit/test_pfs_integration.py
Labels: dev: Please Review

#3806 Fixed tools/startcluster.py
  raiden/tests/utils/eth_node.py
Labels: dev: Please Review

#3807 removed unecessary utility
  raiden/tests/integration/fixtures/raiden_network.py
  raiden/waiting.py
Labels: dev: Please Review

#3794 Extended docs for the checkout job [skip ci]
  .circleci/config.yml
Labels: dev: Please Review

#3776 Simplified get_onchain_locksroots
  raiden/blockchain_events_handler.py
  raiden/network/proxies/utils.py
  raiden/storage/migrations/v19_to_v20.py
Labels: dev: Please Review

#3821 Additional typing
  raiden/network/discovery.py
  raiden/network/sockfactory.py
  raiden/transfer/merkle_tree.py
  raiden/utils/__init__.py
  raiden/utils/typing.py
Labels: dev: Please Review

#3809 Refactor test eth node infrastructure
  .circleci/config.yml
  raiden/accounts.py
  raiden/constants.py
  raiden/network/rpc/client.py
  raiden/network/rpc/smartcontract_proxy.py
  raiden/network/utils.py
  raiden/settings.py
  raiden/smoketest_genesis.json
  raiden/tests/conftest.py
  raiden/tests/fixtures/variables.py
  raiden/tests/integration/cli/conftest.py
  raiden/tests/integration/cli/test_cli_production.py
  raiden/tests/integration/fixtures/blockchain.py
  raiden/tests/unit/test_cli.py
  raiden/tests/utils/eth_node.py
  raiden/tests/utils/genesis.py
  raiden/tests/utils/smoketest.py
  raiden/tests/utils/transport.py
  raiden/ui/cli.py
  raiden/utils/cli.py
  raiden/utils/http.py
Labels: dev: Please Review

#3822 Improve typing in transport module
  raiden/constants.py
  raiden/messages.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/udp/healthcheck.py
  raiden/network/transport/udp/udp_transport.py
Labels: dev: Please Review

#3824 Fix deployment error due to #3809
  MANIFEST.in
  raiden.spec
  raiden/tests/utils/smoketest.py
Labels: dev: Please Review

#3827 Don't skip tests on git tag triggered builds
  .circleci/conditional_skip.sh
Labels: dev: Please Review

#3795 ci: linting before tests
  .circleci/config.yml
Labels: dev: Please Review

#3828 Move CI PyPI deployment to after binary building
  .circleci/config.yml
Labels: dev: Please Review

#3826 Fixed test race condition
  raiden/tests/integration/long_running/test_settlement.py
Labels: dev: Please Review

#3834 Mypy work on transfer/events.py
  raiden/transfer/events.py
  raiden/utils/__init__.py
Labels: dev: Please Review

#3841 mypy: Fix errors regarding Locksroot and TransactionHash
  Makefile
  raiden/transfer/state_change.py
  raiden/utils/serialization.py
Labels: dev: Please Review

#3829 Update SP assert_pfs_history task
  raiden/settings.py
  tools/scenario-player/scenario_player/tasks/services.py
  tools/scenario-player/scenario_player/ui.py
Labels: scenario player, testing

#3846 Use local interface for geth/parity
  raiden/tests/integration/fixtures/blockchain.py
  raiden/tests/utils/eth_node.py
Labels: dev: Please Review

#3844 Improve balance proof update handling for services
  raiden/raiden_service.py
  raiden/tests/unit/transfer/test_state_diff.py
  raiden/transfer/views.py
Labels: dev: Please Review

#3823 integration tests wait on all smoketests
  .circleci/config.yml
Labels: needs discussion

#3817 Integrations tests raise if an app crashes
  raiden/tests/integration/api/test_pythonapi.py
  raiden/tests/integration/api/test_pythonapi_regression.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/long_running/test_token_networks.py
  raiden/tests/integration/test_balance_proof_check.py
  raiden/tests/integration/test_blockchainservice.py
  raiden/tests/integration/test_echo_node.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/integration/test_raidenservice.py
  raiden/tests/integration/test_regression.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/integration/transfer/test_mediatedtransfer.py
  raiden/tests/integration/transfer/test_mediatedtransfer_events.py
  raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
  raiden/tests/integration/transfer/test_refund_invalid.py
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/tests/utils/detect_failure.py
Labels: dev: Please Review

#3851 Mypy work - 3
  constraints-dev.txt
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/state.py
  raiden/transfer/state_change.py
  raiden/utils/serialization.py
Labels: dev: Please Review

#3870 Remove mypy errors related to TokenNetwork*
  Makefile
  raiden/network/proxies/payment_channel.py
  raiden/network/proxies/token_network.py
  raiden/routing.py
  raiden/settings.py
  raiden/tests/unit/test_version_check.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/transfer/views.py
Labels: dev: Please Review

#3859 Added GenesisDescription
  raiden/tests/integration/fixtures/blockchain.py
  raiden/tests/utils/eth_node.py
  raiden/tests/utils/smoketest.py
  tools/startcluster.py
Labels: dev: Please Review

#3847 Extended asserts
  raiden/tests/conftest.py
  raiden/tests/utils/transfer.py
  raiden/utils/typing.py
Labels: dev: Please Review

#3883 Add mypy to lint task
  .circleci/config.yml
  Makefile
Labels: dev: Please Review

#3854 increase test_cli_change_environment_type timeout
  raiden/tests/integration/cli/test_cli_development.py
Labels: dev: Please Review

#3898 Increase test's settle timeout
  raiden/tests/integration/long_running/test_token_networks.py
Labels: dev: Please Review

#3900 tests: added assert to the transfer util
  raiden/tests/utils/transfer.py
Labels: dev: Please Review

#3896 Some wording fixes in is_transaction_effect_satisfied
  raiden/transfer/node.py
Labels: dev: Please Review

#3899 Removes IOU Bug from Client
  raiden/network/pathfinding.py
  raiden/tests/unit/test_pfs_integration.py
Labels: dev: Please Review

#3911 Fix unlock_account_with_passwordfile for empty password files
  raiden/tests/unit/test_accounts.py
  raiden/ui/prompt.py
Labels: dev: Please Review

#3901 Fix recovery happy case race
  raiden/tests/integration/test_recovery.py
  raiden/tests/utils/transfer.py
Labels: dev: Please Review

#3913 Fix mypy errors for `blockchain_service.py`
  raiden/network/blockchain_service.py
Labels: dev: Please Review

#3725 Extract user/address mapping and presence handling from Matrix transport
  raiden/network/transport/matrix/__init__.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/unit/test_matrix_presence.py
Labels: dev: Please Review, matrix

#3929 integration test for #3915
  raiden/tests/integration/test_regression.py
Labels: dev: Please Review

#3932 Make tests node executor logging less threatening
  raiden/utils/http.py
Labels: dev: Please Review

#3941 Startup functions simplifications
  raiden/tests/unit/test_startup.py
  raiden/ui/app.py
  raiden/ui/startup.py
Labels: dev: Please Review

#3957 Fixed secret registration
  raiden/network/proxies/secret_registry.py
  raiden/raiden_event_handler.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/network/proxies/test_secret_registry.py
  raiden/tests/integration/test_regression.py
  raiden/tests/integration/transfer/test_mediatedtransfer.py
Labels: dev: Please Review

#3962 Actually run migrations v21 to v22
  raiden/utils/upgrades.py
Labels: dev: Please Review

#3965 Properly type account/key operations
  raiden/accounts.py
  raiden/utils/__init__.py
Labels: dev: Please Review

#3712 Add send_to_device method to matrix transport.
  raiden/encoding/messages.py
  raiden/messages.py
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
Labels: dev: Please Review, matrix
