Repository raiden-network/raiden, pull requests merged in 2019-03, with the labels that each got.

#3589 Disable debug logfile in automated ci tests
  raiden/tests/integration/cli/conftest.py
Labels: dev: Please Review

#3587 Skip test when running `pytest --pdb`
  raiden/tests/integration/test_matrix_transport.py
Labels: dev: Please Review

#3585 logging: Added logs for the runnables lifetime
  raiden/api/rest.py
  raiden/network/transport/udp/udp_transport.py
Labels: dev: Please Review

#3595 lint: checking for gevent.waitall usage
  .pylint.rc
  Makefile
  raiden/api/python.py
  raiden/connection_manager.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/integration/contracts/test_secret_registry.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/integration/test_regression.py
  raiden/tests/utils/network.py
  raiden/utils/echo_node.py
  tools/__init__.py
  tools/pylint/__init__.py
  tools/pylint/gevent_checker.py
Labels: dev: Please Review

#3583 Fix Scenario Player release download
  raiden/log_config.py
  raiden/tests/unit/test_cli.py
  raiden/utils/__init__.py
  tools/scenario-player/scenario_player/main.py
  tools/scenario-player/scenario_player/node_support.py
Labels: dev: Please Review, scenario player

#3455 Tampering with RequestMonitoring
  raiden/tests/unit/test_messages.py
Labels: dev: Please Review, safety

#3603 Fix spawn transport
  raiden/tests/utils/transport.py
Labels: dev: Please Review

#3584 Add *dict* serialization methods to CanonicalIdentifier
  raiden/utils/__init__.py
Labels: dev: Please Review

#3611 Use contract name in assert_events
  tools/scenario-player/scenario_player/tasks/blockchain.py
Labels: dev: Please Review

#3621 Update file names in install guide
  docs/overview_and_guide.rst
Labels: dev: Please Review

#3620 Silence pylint warnings
  raiden/transfer/state.py
Labels: dev: Please Review

#3625 CanonicalIdentifier in `raiden.transfer.utils`
  raiden/raiden_event_handler.py
  raiden/tests/unit/test_sqlite.py
  raiden/transfer/utils.py
Labels: dev: Please Review

#3629 Reduce parity `stepDuration` in integration tests
  raiden/tests/utils/genesis.py
Labels: dev: Please Review

#3598 Fix #3588
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/conftest.py
  raiden/tests/fixtures/variables.py
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/test_matrix_transport.py
Labels: dev: Please Review, matrix

#3642 Update coincurve to 11.0
  constraints.txt
Labels: dev: Please Review

#3640 Use wait_assert utility together with assert_synced_channel_state
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
  raiden/tests/integration/transfer/test_refundtransfer.py
Labels: dev: Please Review

#3626 added lint check for unused argument
  .pylint.rc
  raiden/api/python.py
  raiden/api/rest.py
  raiden/api/v1/encoding.py
  raiden/log_config.py
  raiden/messages.py
  raiden/network/proxies/payment_channel.py
  raiden/network/proxies/token.py
  raiden/network/proxies/token_network.py
  raiden/network/proxies/token_network_registry.py
  raiden/network/rpc/middleware.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/storage/sqlite.py
  raiden/tests/conftest.py
  raiden/tests/fixtures/variables.py
  raiden/tests/integration/fixtures/raiden_network.py
  raiden/tests/integration/fixtures/smartcontracts.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/long_running/test_token_networks.py
  raiden/tests/integration/network/proxies/test_payment_channel.py
  raiden/tests/integration/network/proxies/test_token.py
  raiden/tests/integration/network/proxies/test_token_network.py
  raiden/tests/integration/network/proxies/test_token_network_registry.py
  raiden/tests/integration/network/transport/test_udp.py
  raiden/tests/integration/test_balance_proof_check.py
  raiden/tests/integration/test_matrix_transport.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/integration/transfer/test_mediatedtransfer.py
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/tests/unit/api/test_api.py
  raiden/tests/unit/storage/migrations/test_v18_to_v19.py
  raiden/tests/unit/test_accounts.py
  raiden/tests/unit/test_matrix_transport.py
  raiden/tests/unit/test_node_queue.py
  raiden/tests/unit/test_pfs_integration.py
  raiden/tests/unit/test_raiden_event_handler.py
  raiden/tests/unit/test_sqlite.py
  raiden/tests/unit/test_tokennetwork.py
  raiden/tests/unit/test_version_check.py
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
  raiden/tests/utils/factories.py
  raiden/tests/utils/mocks.py
  raiden/tests/utils/network.py
  raiden/tests/utils/protocol.py
  raiden/tests/utils/smartcontracts.py
  raiden/tests/utils/smoketest.py
  raiden/tests/utils/transport.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/node.py
  raiden/transfer/token_network.py
  raiden/ui/console.py
  raiden/utils/cli.py
Labels: dev: Please Review

#3639 Added autopep8 as a linting tool
  Makefile
  raiden/network/sockfactory.py
  requirements-lint.txt
Labels: dev: Please Review

#3646 Update contracts to 0.15.0
  constraints.txt
  raiden/settings.py
Labels: dev: Please Review

#3655 removed unnecessary wait calls
  raiden/tests/integration/test_balance_proof_check.py
Labels: dev: Please Review

#3654 tigthened try-block
  raiden/network/sockfactory.py
Labels: dev: Please Review

#3652 Fixed event handler type annotation
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#3648 Revert unecessary changes from 00a86560dceae5119
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/long_running/test_settlement.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/integration/test_recovery.py
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/integration/transfer/test_mediatedtransfer_invalid.py
Labels: dev: Please Review

#3662 clarified MS update [skip ci]
  raiden/raiden_service.py
Labels: dev: Please Review

#3669 Move versions back into requirements file
  requirements.txt
Labels: dev: Please Review

#3672 Use proper url to call the pathfinding service
  raiden/network/pathfinding.py
Labels: dev: Please Review

#3675 [SP] Fix event assertions on token network contract
  tools/scenario-player/scenario_player/runner.py
  tools/scenario-player/scenario_player/tasks/blockchain.py
Labels: dev: Please Review

#3679 Replace SerializedSQLiteStorage with raw SQLiteStorage
  raiden/tests/unit/storage/migrations/test_v19_to_v20.py
Labels: dev: Please Review

#3689 Fix upgrade manager
  raiden/tests/unit/storage/migrations/test_v16_to_v17.py
  raiden/tests/unit/storage/migrations/test_v17_to_v18.py
  raiden/tests/unit/storage/migrations/test_v18_to_v19.py
  raiden/tests/unit/storage/migrations/test_v19_to_v20.py
  raiden/tests/unit/test_upgrade.py
  raiden/utils/upgrades.py
Labels: dev: Please Review

#3690 Use raiden-contracts v0.16.0 and remove the temporal fix
  constraints.txt
  raiden/ui/app.py
Labels: dev: Please Review

#3385 First chunk of #3124
  raiden/tests/conftest.py
  raiden/tests/integration/test_matrix_transport.py
Labels: dev: Please Review, matrix

#3698 Declare raiden to be typed via PEP561
  raiden/py.typed
  setup.py
Labels: dev: Please Review

#3695 Use raiden-contracts v0.17.0 and introduce click 7.0
  constraints.txt
  requirements.txt
Labels: dev: Please Review

#3688 Fix startup for private networks
  raiden/ui/app.py
Labels: dev: Please Review

#3706 Fix ui/app.py initialization
  raiden/ui/app.py
Labels: dev: Please Review

#3704 Update web3 and related dependencies
  constraints.txt
  requirements.txt
Labels: dev: Please Review
