Repository raiden-network/raiden, pull requests merged in 2019-11, with the labels that each got.

#5200 Add a check to notify about the monitoring contract requirement
  raiden/ui/app.py
Labels: PR / Awaiting Review

#5211 Remove unused Py2 version of Matrix eth_auth_provider
  tools/eth_auth_provider.py2
Labels: Component / Transport, PR / Awaiting Review

#5222 Removed _getroom_lock
  raiden/network/transport/matrix/transport.py
Labels: PR / Awaiting Review

#5224 Extended docs for `_get_user` [skip tests]
  raiden/network/transport/matrix/transport.py
Labels: PR / Awaiting Review

#5223 removed unused flag [skip tests]
  raiden/network/transport/matrix/transport.py
Labels: PR / Awaiting Review

#5226 Enable strict type checks for raiden.api.rest
  raiden/api/rest.py
  setup.cfg
Labels: PR / Awaiting Review

#5228 `_get_room_ids_for_address` changes
  raiden/network/transport/matrix/transport.py
Labels: PR / Awaiting Review

#5241 Fix runtime error: dict modified while iterating
  raiden/network/transport/matrix/utils.py
  raiden/tests/unit/test_matrix_presence.py
Labels: PR / Awaiting Review

#5251 Removed extra call to `set_presence_state`
  raiden/network/transport/matrix/utils.py
Labels: PR / Awaiting Review

#5225 displayname cache rewrite.
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/mocked/test_matrix_transport.py
  raiden/tests/unit/test_matrix_presence.py
Labels: PR / Awaiting Review

#5262 Fix matrix test helper
  raiden/tests/utils/transport.py
Labels: PR / Awaiting Review

#5289 Remove unused code from the ProxyManager
  raiden/network/proxies/proxy_manager.py
  raiden/tests/integration/long_running/test_settlement.py
Labels: PR / Awaiting Review

#5288 Remove unused function from smartcontract_proxy
  raiden/network/rpc/smartcontract_proxy.py
Labels: PR / Awaiting Review

#5291 Skip test_regression_unfiltered_routes as flaky
  raiden/tests/integration/test_regression.py
Labels: PR / Awaiting Review

#5290 Increase coverage of raiden/utils/ethereum_clients.py
  raiden/tests/unit/test_cli.py
Labels: PR / Awaiting Review

#5287 PR template should explain what issue is fixed inside description
  .github/pull_request_template.md
Labels: PR / Awaiting Review

#5286 Increase test coverage for network/rpc/transactions.py
  raiden/network/rpc/transactions.py
  raiden/tests/unit/test_rpc.py
Labels: PR / Awaiting Review

#5316 Add some of the tests missing from the REST API
  raiden/tests/integration/api/test_restapi.py
Labels: PR / Awaiting Review

#5333 Update the URLs for the known matrix servers
  raiden/settings.py
Labels: PR / Awaiting Review

#5358 CI: Never skip non-PR builds
  .circleci/conditional_skip.sh
Labels: Component / CI, PR / Awaiting Review

#5372 Fix analyze_sp_logs script
  tools/debugging/analyze_sp_logs.py
Labels: PR / Awaiting Review
