Repository raiden-network/raiden, pull requests merged in 2019-05, with the labels that each got.

#3815 ADR: Git Workflow
  docs/adr/0003-git-workflow.rst
  docs/adr/overview.rst
Labels: dev: Please Review

#3985 fixed use before assignment
  raiden/ui/checks.py
  raiden/ui/startup.py
Labels: dev: Please Review

#3995 rename secret_hash to be secrethash
  raiden/api/python.py
  raiden/api/rest.py
  raiden/constants.py
  raiden/message_handler.py
  raiden/network/resolver/client.py
  raiden/raiden_service.py
  raiden/tests/integration/api/test_restapi.py
  raiden/tests/integration/test_echo_node.py
  raiden/transfer/mediated_transfer/state.py
Labels: dev: Please Review

#3987 updated transfer does not raise ChannelOutdated anymore
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#4001 Make sure isort and black do not interfere
  setup.cfg
Labels: dev: Please Review

#3979 Unit test refactoring (follow-up pr)
  raiden/tests/fuzz/test_state_changes.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/integration/transfer/test_mediatedtransfer.py
  raiden/tests/integration/transfer/test_refund_invalid.py
  raiden/tests/unit/api/test_api.py
  raiden/tests/unit/test_binary_encoding.py
  raiden/tests/unit/test_channelstate.py
  raiden/tests/unit/test_dict_encoding.py
  raiden/tests/unit/test_messages.py
  raiden/tests/unit/test_node_queue.py
  raiden/tests/unit/test_pfs_integration.py
  raiden/tests/unit/test_sqlite.py
  raiden/tests/unit/test_tokennetwork.py
  raiden/tests/unit/transfer/mediated_transfer/test_events.py
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
  raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
  raiden/tests/utils/factories.py
  raiden/tests/utils/messages.py
  raiden/tests/utils/mocks.py
  raiden/tests/utils/transfer.py
Labels: dev: Please Review, testing

#4011 Move old scenarios to separate folder
  raiden/tests/scenarios/old_scenarios/Scenario-Kill-Receiver.yaml
  raiden/tests/scenarios/old_scenarios/Scenario-Mediated-Transfer-in-Hexagon.yaml
  raiden/tests/scenarios/old_scenarios/Scenario-Re-Routing.yaml
  raiden/tests/scenarios/old_scenarios/close_channel_all_channels.yaml
  raiden/tests/scenarios/old_scenarios/close_channel_one_channel.yaml
  raiden/tests/scenarios/old_scenarios/close_channel_reopen_before_settle.yaml
  raiden/tests/scenarios/old_scenarios/direct_transfers_happy_cases_1-1000_txs.yaml
  raiden/tests/scenarios/old_scenarios/direct_transfers_mixed_edge_cases.yaml
  raiden/tests/scenarios/old_scenarios/direct_transfers_stopped_node_scenarios.yaml
  raiden/tests/scenarios/old_scenarios/funding-channel-scenarios.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J1.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J10.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J11.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J12.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J13.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J15.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J16.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J17.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J18.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J19.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J2.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J3.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J4.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J6.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J7.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J8.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J9.yaml
  raiden/tests/scenarios/old_scenarios/leave-network-happy-scenario.yaml
  raiden/tests/scenarios/old_scenarios/leave-network-on-closed_channels.yaml
  raiden/tests/scenarios/old_scenarios/leave-network-with-stopped-node.yaml
  raiden/tests/scenarios/old_scenarios/mediated-transfers-scnenarios.yaml
  raiden/tests/scenarios/old_scenarios/open-channel-different-scenarios.yaml
Labels: dev: Please Review, scenario player

#4015 Fix makefile paths after removal of scenario_player
  Makefile
  tools/genesis_builder.py
Labels: dev: Please Review

#4016 Add simple scenarios for the services
  raiden/tests/scenarios/ms1_simple_monitoring.yaml
  raiden/tests/scenarios/ms2_simple_monitoring.yaml
  raiden/tests/scenarios/ms3_simple_monitoring.yaml
  raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
  raiden/tests/scenarios/pfs2_simple_no_path.yaml
  raiden/tests/scenarios/pfs3_multiple_paths.yaml
  raiden/tests/scenarios/pfs4_use_best_path.yaml
  raiden/tests/scenarios/pfs5_too_low_capacity.yaml
  raiden/tests/scenarios/pfs6_low_capacity.yaml
  raiden/tests/scenarios/pfs7_simple_path_rewards.yaml
Labels: dev: Please Review, scenario player

#4025 Use mypy target in lint
  Makefile
Labels: dev: Please Review

#4023 Fix types in pathfinding and routing
  raiden/network/pathfinding.py
  raiden/routing.py
  raiden/tests/unit/test_pfs_integration.py
Labels: dev: Please Review

#4038 Add more type annotation in raiden.transfer
  raiden/transfer/architecture.py
  raiden/transfer/events.py
  raiden/transfer/identifiers.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/state.py
  raiden/transfer/mediated_transfer/state_change.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/transfer/state_change.py
  raiden/transfer/token_network.py
  raiden/transfer/views.py
Labels: dev: Please Review

#4034 Uses direct routing when direct channel exists, no pfs request
  raiden/routing.py
  raiden/tests/unit/test_pfs_integration.py
  raiden/tests/unit/test_tokennetwork.py
Labels: dev: Please Review

#4045 Fixed some channel.py type annotations
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review

#4060 Cleanups to service and initiator manager
  raiden/raiden_service.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/mediated_transfer/state_change.py
Labels: dev: Please Review

#4002 Add docker hub build trigger to nightly workflow.
  .circleci/config.yml
Labels: dev: Please Review

#4022 Submit code coverage for different test types with flags
  .circleci/config.yml
Labels: dev: Please Review

#4066 Make pylint pick up all settings by default
  Makefile
  pylintrc
Labels: dev: Please Review

#4067 More annotation
  raiden/network/rpc/client.py
  raiden/network/rpc/transactions.py
  raiden/tests/unit/test_cli.py
  raiden/utils/__init__.py
  raiden/utils/notifying_queue.py
  raiden/utils/runnable.py
  raiden/utils/serialization.py
  raiden/utils/signing.py
  raiden/utils/solc.py
Labels: dev: Please Review

#4081 Add missing exception type in ec-recover wrapper
  raiden/tests/unit/test_utils.py
  raiden/utils/signer.py
Labels: dev: Please Review

#4092 Show checksummed address in password promt
  raiden/ui/prompt.py
Labels: dev: Please Review

#3981 Improve transport logging and remove unused path in leave_unused_rooms
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
Labels: dev: Please Review, matrix

#4112 Allow populating user to address mapping from server directory
  raiden/network/transport/matrix/utils.py
  raiden/tests/unit/test_matrix_presence.py
Labels: PFS, dev: Please Review, matrix

#4113 typing information for the proxies
  raiden/network/blockchain_service.py
  raiden/network/discovery.py
  raiden/network/proxies/discovery.py
  raiden/network/proxies/payment_channel.py
  raiden/network/proxies/service_registry.py
  raiden/network/proxies/token.py
  raiden/network/proxies/token_network.py
  raiden/network/proxies/user_deposit.py
  raiden/network/rpc/client.py
  raiden/tests/utils/smoketest.py
  raiden/ui/app.py
  raiden/utils/__init__.py
  raiden/utils/typing.py
Labels: dev: Please Review

#4115 enabled stack trace printing for smoketest
  raiden/tests/conftest.py
  raiden/ui/cli.py
  raiden/utils/debugging.py
Labels: dev: Please Review

#4114 Assumption tests for bad output
  raiden/tests/integration/rpc/assumptions/test_rpc_call_assumptions.py
  raiden/tests/smart_contracts/RpcTest.sol
Labels: dev: Please Review

#4091 Add changelog entries
  docs/changelog.rst
Labels: dev: Please Review

#4096 Log debug information when requesting PFS
  raiden/network/pathfinding.py
Labels: dev: Please Review

#4094 Remove Optional from cmdid type definition
  raiden/messages.py
Labels: dev: Please Review

#4120 Maintaining vim's backup file around
  Makefile
Labels: dev: Please Review

#4121 Follow-up fixes to removing UDP
  .circleci/config.yml
  raiden/tests/README.rst
  raiden/tests/conftest.py
  raiden/ui/cli.py
Labels: dev: Please Review

#4119 Bump version 0.100.3
  .bumpversion_client.cfg
  docs/changelog.rst
  docs/conf.py
  setup.py
Labels: dev: Please Review

#4122 use blocks instead of seconds for wait in ms scenarios
  raiden/tests/scenarios/ms1_simple_monitoring.yaml
  raiden/tests/scenarios/ms2_simple_monitoring.yaml
  raiden/tests/scenarios/ms3_simple_monitoring.yaml
Labels: dev: Please Review

#4101 Dataclasses - Remove some disable E1101
  raiden/raiden_service.py
  raiden/tests/unit/test_channelstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_events.py
  raiden/transfer/mediated_transfer/state.py
Labels: dev: Please Review

#4129 Unify next_channel_from_routes for initiator and mediator
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/tests/utils/factories.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#3848 lint: enforce decreasing number of errors
  .circleci/config.yml
  .circleci/enforce_decreasing_lint_errors.sh
Labels: dev: Please Review, needs discussion

#4106 Unit test for MessageHandler class
  raiden/tests/unit/test_messages.py
  raiden/tests/utils/factories.py
Labels: dev: Please Review, testing

#4133 Small changes to payment channel proxy
  raiden/network/proxies/README.md
  raiden/network/proxies/payment_channel.py
Labels: dev: Please Review

#4139 Rename EMPTY_SECRET into ABSENT_SECRET
  raiden/constants.py
  raiden/message_handler.py
  raiden/raiden_service.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/views.py
Labels: dev: Please Review

#4134 Remove `unpack` method from messages
  raiden/messages.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/tests/unit/test_binary_encoding.py
  raiden/tests/unit/test_messages.py
Labels: dev: Please Review

#4148 Upgrade pylint to fix spurious ci failures
  constraints-dev.txt
  requirements-lint.txt
Labels: dev: Please Review

#4146 Update old scenarios to v2
  raiden/tests/scenarios/old_scenarios/Scenario-Kill-Receiver.yaml
  raiden/tests/scenarios/old_scenarios/Scenario-Mediated-Transfer-in-Hexagon.yaml
  raiden/tests/scenarios/old_scenarios/Scenario-Re-Routing.yaml
  raiden/tests/scenarios/old_scenarios/close_channel_all_channels.yaml
  raiden/tests/scenarios/old_scenarios/close_channel_one_channel.yaml
  raiden/tests/scenarios/old_scenarios/close_channel_reopen_before_settle.yaml
  raiden/tests/scenarios/old_scenarios/direct_transfers_happy_cases_1-1000_txs.yaml
  raiden/tests/scenarios/old_scenarios/direct_transfers_mixed_edge_cases.yaml
  raiden/tests/scenarios/old_scenarios/direct_transfers_stopped_node_scenarios.yaml
  raiden/tests/scenarios/old_scenarios/funding-channel-scenarios.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J1.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J10.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J11.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J12.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J13.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J15.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J16.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J17.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J18.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J19.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J2.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J3.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J4.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J6.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J7.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J8.yaml
  raiden/tests/scenarios/old_scenarios/join-network-scenario-J9.yaml
  raiden/tests/scenarios/old_scenarios/leave-network-happy-scenario.yaml
  raiden/tests/scenarios/old_scenarios/leave-network-on-closed_channels.yaml
  raiden/tests/scenarios/old_scenarios/leave-network-with-stopped-node.yaml
  raiden/tests/scenarios/old_scenarios/mediated-transfers-scnenarios.yaml
  raiden/tests/scenarios/old_scenarios/open-channel-different-scenarios.yaml
  raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
  raiden/tests/scenarios/pfs2_simple_no_path.yaml
  raiden/tests/scenarios/pfs3_multiple_paths.yaml
  raiden/tests/scenarios/pfs4_use_best_path.yaml
  raiden/tests/scenarios/pfs5_too_low_capacity.yaml
  raiden/tests/scenarios/pfs6_low_capacity.yaml
  raiden/tests/scenarios/pfs7_simple_path_rewards.yaml
Labels: dev: Please Review

#4155 update disclaimer
  docs/index.rst
Labels: dev: Please Review

#4157 Remove some unnecessary dependencies
  constraints.txt
  requirements.txt
Labels: dev: Please Review

#4160 Improve typing of RaidenService
  raiden/constants.py
  raiden/network/resolver/client.py
  raiden/network/transport/matrix/transport.py
  raiden/raiden_service.py
  raiden/storage/sqlite.py
  raiden/storage/wal.py
Labels: dev: Please Review

#4159 Fix precedence for CLI options / config file settings
  raiden/utils/cli.py
Labels: dev: Please Review

#4162 Use deploy_rpc_test_contract consistently in assumption tests
  raiden/tests/integration/rpc/assumptions/test_parity_rpc_assumptions.py
  raiden/tests/integration/rpc/assumptions/test_rpc_call_assumptions.py
  raiden/tests/integration/rpc/assumptions/test_rpc_filters_assumptions.py
  raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
  raiden/tests/integration/rpc/assumptions/test_rpc_gas_price_assumptions.py
  raiden/tests/integration/rpc/assumptions/test_rpc_transaction_assumptions.py
  raiden/tests/integration/test_regression_parity.py
  raiden/tests/utils/smartcontracts.py
Labels: dev: Please Review
