Repository raiden-network/raiden, pull requests merged in 2019-07, with the labels that each got.

#4313 Increase timeout for `test_send_queued_messages`.
  raiden/tests/integration/test_send_queued_messages.py
Labels: dev: Please Review

#4305 Use PFS routing by default
  raiden/tests/integration/cli/conftest.py
  raiden/ui/cli.py
Labels: dev: Please Review

#4308 Add docstring to `EnvelopeMessage`
  raiden/messages.py
Labels: dev: Please Review

#4315 Remove outdated comment
  raiden/messages.py
Labels: dev: Please Review

#4316 use local venv instead of nightlies [skip tests]
  raiden/tests/scenarios/ms1_simple_monitoring.yaml
  raiden/tests/scenarios/ms2_simple_monitoring.yaml
  raiden/tests/scenarios/ms3_simple_monitoring.yaml
  raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
  raiden/tests/scenarios/pfs2_simple_no_path.yaml
  raiden/tests/scenarios/pfs3_multiple_paths.yaml
  raiden/tests/scenarios/pfs4_use_best_path.yaml
  raiden/tests/scenarios/pfs5_too_low_capacity.yaml
  raiden/tests/scenarios/pfs6_low_capacity.yaml
  raiden/tests/scenarios/pfs7_simple_path_rewards.yaml
Labels: dev: Please Review

#4323 Added humand readable ULID representation
  raiden/storage/ulid.py
Labels: dev: Please Review

#4329 Fixed race condition on test_send_queued
  raiden/tests/integration/test_send_queued_messages.py
Labels: dev: Please Review

#4324 Consistent logging for waiting functions
  raiden/waiting.py
Labels: dev: Please Review

#4331 The smart contract does not allow for the channel with id 0
  raiden/messages.py
Labels: dev: Please Review

#4332 removed unused function
  raiden/messages.py
Labels: dev: Please Review

#4217 State pruning in token proxy
  raiden/network/proxies/token.py
Labels: dev: Please Review, state-pruning

#4322 Use logging instead of print
  raiden/tests/utils/detect_failure.py
Labels: dev: Please Review

#4302 Use `FeeSchedule` for incoming channel
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#4341 Add flaky package and mark flaky tests
  raiden/tests/integration/long_running/test_token_networks.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  requirements/requirements-ci.txt
  requirements/requirements-dev.in
  requirements/requirements-dev.txt
Labels: dev: Please Review

#4349 Change method of getting json data out of HTTP requests
  raiden/network/pathfinding.py
  raiden/network/resolver/client.py
  raiden/tests/integration/api/test_restapi.py
  raiden/tests/unit/test_pfs_integration.py
  raiden/tests/utils/mocks.py
  raiden/tests/utils/smoketest.py
  raiden/ui/sync.py
Labels: dev: Please Review

#4334 Update marshmallow versions
  raiden/api/v1/encoding.py
  raiden/storage/serialization/cache.py
  raiden/storage/serialization/fields.py
  requirements/requirements-ci.txt
  requirements/requirements-dev.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: dev: Work In Progress

#4357 Fix setup.py for readme change to markdown
  setup.py
Labels: dev: Please Review

#4353 Update PFS7 scenario and fix a user-visible output
  raiden/network/pathfinding.py
  raiden/tests/scenarios/pfs7_simple_path_rewards.yaml
Labels: dev: Please Review

#4354 Cleanup after signing changed
  raiden/messages.py
Labels: dev: Please Review

#4370 Mark flaky tests as flaky
  raiden/tests/integration/api/test_restapi.py
  raiden/tests/integration/test_echo_node.py
  raiden/tests/integration/test_send_queued_messages.py
Labels: dev: Please Review

#4294 Update latest file pointer generation
  .circleci/config.yml
  .circleci/get_archive_tag.sh
  .circleci/upload_to_s3.sh
Labels: dev: Please Review

#4363 collapsed functions to check signature
  raiden/transfer/channel.py
Labels: dev: Please Review

#4376 Rename occurrences of newbalance to deposit
  raiden/api/python.py
  raiden/blockchain/decode.py
  raiden/blockchain_events_handler.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/integration/test_pythonapi.py
  raiden/tests/unit/test_channelstate.py
  raiden/tests/unit/test_data/db_statechanges.json
  raiden/tests/unit/test_state.py
  raiden/tests/utils/network.py
  raiden/transfer/channel.py
  raiden/transfer/node.py
  raiden/transfer/state.py
  raiden/transfer/state_change.py
  raiden/transfer/token_network.py
  raiden/waiting.py
Labels: dev: Please Review

#4384 Update contracts versions in `raiden/settings.py`
  raiden/settings.py
Labels: dev: Please Review

#4385 Fix call to set total deposit in case block is pruned
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#4387 Fix global queue handling during transport startup
  raiden/network/transport/matrix/transport.py
Labels: dev: Please Review, matrix

#4395 Cast imbalance fees to `int` and then `FeeAmount`
  raiden/transfer/mediated_transfer/mediation_fee.py
Labels: dev: Please Review

#4400 Fixed race condition on test with entire deposit
  raiden/tests/integration/transfer/test_mediatedtransfer.py
Labels: dev: Please Review

#4389 Added docstrings for un/recoverable exceptions
  raiden/exceptions.py
Labels: dev: Please Review

#4404 mark stress test as flaky #4380
  raiden/tests/integration/long_running/test_stress.py
Labels: dev: Please Review

#4409 Upgraded parity on CI to 2.5.5
  .circleci/config.yml
  .circleci/fetch_geth_parity_solc.sh
Labels: dev: Please Review

#4416 Give more feedback for flaky tests
  raiden/tests/conftest.py
Labels: dev: Please Review, testing

#4392 Blockchain exception
  raiden/blockchain/events.py
  raiden/blockchain/exceptions.py
  raiden/exceptions.py
Labels: dev: Please Review

#4415 Added test for the estimate gas behavior.
  raiden/tests/integration/rpc/assumptions/test_rpc_gas_estimation_assumptions.py
  raiden/tests/smart_contracts/RpcWithStorageTest.sol
Labels: dev: Please Review

#4411 Extended logging for the HTTPExecutor
  raiden/utils/http.py
Labels: dev: Please Review

#4408 Disable hack to trim logs
  raiden/tests/integration/long_running/test_stress.py
Labels: dev: Please Review

#4422 Fixed flaky test test_payment_statuses_are_restored
  raiden/tests/integration/test_send_queued_messages.py
  raiden/tests/utils/protocol.py
Labels: dev: Please Review

#4430 Fix flaky test reporter
  raiden/tests/conftest.py
Labels: dev: Please Review, testing

#4432 Reduce the number of transfers in `test_stress`
  raiden/tests/integration/long_running/test_stress.py
Labels: dev: Please Review

#4428 Improvements to timeout option handling
  raiden/tests/conftest.py
Labels: dev: Please Review

#4438 Changes pfs7 scenario to source routing
  raiden/tests/scenarios/pfs7_simple_path_rewards.yaml
Labels: scenario player

#4437 Unskip `test_echo_node_lottery`
  raiden/tests/integration/test_echo_node.py
Labels: dev: Please Review

#4441 Skip `test_stress` until is runs reliably
  raiden/tests/integration/long_running/test_stress.py
Labels: dev: Please Review

#4442 Update mypy to 0.720
  requirements/requirements-ci.txt
  requirements/requirements-dev.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: dev: Please Review

#4453 Skipping test_cli_manual_account_selection
  raiden/tests/integration/cli/test_cli_development.py
Labels: dev: Please Review

#4461 Use debian stretch based image to build linux bundle
  docker/build.Dockerfile
Labels: dev: Please Review

#4467 Unskip cli tests
  raiden/tests/integration/cli/test_cli_development.py
Labels: dev: Please Review

#4433 Take source routing into account
  raiden/tests/scenarios/pfs7_simple_path_rewards.yaml
Labels: dev: Please Review

#4478 Tiny improvement to the local logging folder
  raiden/tests/utils/tests.py
Labels: dev: Please Review

#4480 Support up to geth v1.8.27
  .circleci/config.yml
  raiden/constants.py
Labels: dev: Please Review

#4474 Add typing_extensions to production requirements
  requirements/requirements.in
  requirements/requirements.txt
Labels: dev: Please Review

#4444 Further reduce test_stress deposit to improve reliability
  raiden/tests/integration/long_running/test_stress.py
Labels: dev: Please Review

#4423 Use the packing functions from raiden-contracts
  raiden/utils/packing.py
Labels: dev: Please Review

#4491 Make CI tag regex also recognize dev builds
  .circleci/config.yml
Labels: infrastructure

#4492 Fix the format of latest release for consistency
  .bumpversion_client.cfg
  docs/changelog.rst
  docs/conf.py
  setup.py
Labels: dev: Please Review

#4494 Test failure log declutter
  raiden/tests/utils/detect_failure.py
Labels: dev: Please Review

#4495 Fix KeyError in UserAddressManager
  raiden/network/transport/matrix/utils.py
  raiden/tests/unit/test_matrix_presence.py
Labels: dev: Please Review, matrix

#4496 Add waits into PFS5/6 scenarios
  raiden/tests/scenarios/pfs5_too_low_capacity.yaml
  raiden/tests/scenarios/pfs6_low_capacity.yaml
Labels: dev: Please Review

#4452 Cleanup echo node test
  raiden/api/python.py
  raiden/tests/integration/test_echo_node.py
  raiden/utils/echo_node.py
Labels: dev: Please Review

#4500 Some json-log-to-html improvements
  tools/debugging/json-log-to-html.py
Labels: dev: Please Review
