Repository raiden-network/raiden, pull requests merged in 2019-09, with the labels that each got.

#4707 Remove MONITORING_MIN_CAPACITY check for monitoring
  raiden/services.py
  raiden/settings.py
Labels: dev: Please Review

#4635 Add scenarios for node offline and partial withdraw scenarios
  raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
  raiden/tests/scenarios/pfs9_partial_withdraw.yaml
Labels: dev: Please Review

#4723 Update changelog [skip tests]
  docs/changelog.rst
Labels: dev: Please Review

#4714 Enforce typing by default in `raiden`
  raiden/__main__.py
  raiden/accounts.py
  raiden/app.py
  raiden/blockchain_events_handler.py
  raiden/connection_manager.py
  raiden/log_config.py
  raiden/message_handler.py
  raiden/network/transport/matrix/transport.py
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
  raiden/storage/serialization/cache.py
  raiden/storage/serialization/fields.py
  raiden/storage/serialization/serializer.py
  raiden/storage/sqlite.py
  raiden/storage/ulid.py
  raiden/storage/utils.py
  raiden/tasks.py
  raiden/tests/utils/transfer.py
  raiden/ui/app.py
  raiden/waiting.py
  setup.cfg
  tools/transfer_eth.py
Labels: dev: Please Review

#4693 Treat trying to deposit on a closed channel as recoverable error
  raiden/api/python.py
  raiden/api/rest.py
  raiden/connection_manager.py
  raiden/exceptions.py
  raiden/tests/integration/api/test_pythonapi.py
Labels: dev: Please Review

#4728 Add more logs to the connection manager
  raiden/connection_manager.py
Labels: dev: Please Review

#4726 Fix wrong parameter in connection manager
  raiden/connection_manager.py
Labels: dev: Please Review

#4724 typing for rest.py
  raiden/api/rest.py
Labels: dev: Please Review

#4736 Add additional sections for docs & specs
  .github/pull_request_template.md
Labels: dev: Please Review

#4742 Add more typing to rest API
  raiden/api/rest.py
Labels: dev: Please Review

#4711 Delete state machine doc [skip tests]
  docs/state_machines.rst
Labels: dev: Please Review

#4720 Unify {PRODUCTION,DEVELOPMENT}_CONTRACT_VERSION
  docs/private_net_tutorial.rst
  raiden/api/python.py
  raiden/app.py
  raiden/settings.py
  raiden/tests/fixtures/blockchain.py
  raiden/tests/integration/cli/conftest.py
  raiden/tests/integration/cli/test_cli_development.py
  raiden/tests/integration/cli/test_cli_production.py
  raiden/tests/integration/fixtures/smartcontracts.py
  raiden/tests/utils/smoketest.py
  raiden/ui/cli.py
  raiden/ui/console.py
  raiden/ui/startup.py
  tools/gas_cost_measures.py
Labels: dev: Please Review

#4774 Check `settle_timeout` threshold for success, too
  raiden/tests/integration/network/proxies/test_token_network.py
Labels: dev: Please Review

#4781 Make sure that SendWithdrawRequest is deserializable
  raiden/tests/unit/storage/test_serialization.py
Labels: dev: Please Review

#4787 Fix syntax in PFS8 [skip tests]
  raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
Labels: dev: Please Review

#4812 Fix syntax error in PFS9 scenario
  raiden/tests/scenarios/pfs9_partial_withdraw.yaml
Labels: dev: Please Review

#4799 Add get_token_networks_created()
  raiden/network/proxies/token_network_registry.py
  raiden/tests/integration/network/proxies/test_token_network_registry.py
Labels: dev: Please Review

#4808 Fix wrong assertion and only return one path [skip tests]
  raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
Labels: dev: Please Review

#4820 Add TokenNetworkRegistry.get_max_token_networks()
  raiden/network/proxies/token_network_registry.py
  raiden/tests/integration/network/proxies/test_token_network_registry.py
Labels: dev: Please Review

#4826 Only use one path per request [skip tests]
  raiden/tests/scenarios/pfs9_partial_withdraw.yaml
Labels: dev: Please Review

#4834 Update pfs7 scenario to only match distinct routes
  raiden/tests/scenarios/pfs7_multiple_payments.yaml
Labels: dev: Please Review

#4832 Fix MS4: add tasks keyword [skip tests]
  raiden/tests/scenarios/ms4_udc_too_low.yaml
Labels: dev: Please Review

#4862 Simplify add_token_with_limits()
  raiden/api/python.py
  raiden/network/proxies/token_network_registry.py
  raiden/tests/integration/fixtures/smartcontracts.py
  raiden/tests/integration/network/proxies/test_token_network_registry.py
  raiden/tests/utils/smoketest.py
  raiden/ui/console.py
Labels: dev: Please Review

#4880 Remove an exception that is never thrown
  raiden/api/python.py
  raiden/api/rest.py
  raiden/connection_manager.py
  raiden/exceptions.py
Labels: dev: Please Review

#4871 Transport greenlet generation
  raiden/network/transport/matrix/transport.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
  raiden/utils/runnable.py
Labels: dev: Please Review, matrix

#4914 Add documentation on the balance update delay after initiator return.
  docs/rest_api.rst
Labels: dev: Please Review

#4916 Add secret/secret_hash to payment API response
  docs/rest_api.rst
Labels: dev: Please Review

#4918 Revert assignee for the github bot
  .github/auto_assign.yml
Labels: dev: Please Review

#4941 Update MS/BF scenarios to use new assert_events filters
  raiden/tests/scenarios/bf1_basic_functionality.yaml
  raiden/tests/scenarios/ms1_simple_monitoring.yaml
  raiden/tests/scenarios/ms2_simple_monitoring.yaml
  raiden/tests/scenarios/ms3_simple_monitoring.yaml
  raiden/tests/scenarios/ms4_udc_too_low.yaml
Labels: dev: Please Review

#4876 Avoid adding a token at NULL_ADDRESS
  raiden/api/python.py
  raiden/api/rest.py
  raiden/exceptions.py
  raiden/network/proxies/token_network_registry.py
  raiden/tests/integration/network/proxies/test_token_network_registry.py
Labels: dev: Please Review

#4940 Fix message wording in PFS connection and price advertising
  raiden/network/pathfinding.py
Labels: dev: Please Review

#4929 Fix handlers in node.py to follow naming convention
  raiden/tests/unit/test_node_queue.py
  raiden/tests/unit/transfer/test_node.py
  raiden/tests/unit/transfer/test_source_routing.py
  raiden/tests/utils/protocol.py
  raiden/transfer/node.py
Labels: dev: Please Review

#4920 Flat mediation fee scenario
  raiden/tests/scenarios/README.md
  raiden/tests/scenarios/mfee1_flat_fee.yaml
Labels: dev: Please Review

#4939 Add documentation for normal log config and debug log disabling
  docs/overview_and_guide.rst
Labels: dev: Please Review

#4873 Some notes for proxy implementors
  docs/proxies.rst
Labels: dev: Please Review

#4959 Fix crash in sphinx due to version number
  docs/changelog.rst
Labels: documentation

#4964 RaidenRecoverableError indicates conflicts.
  raiden/api/rest.py
Labels: dev: Please Review

#4956 Remove checks that are not in the onchain contract
  raiden/network/proxies/token_network_registry.py
Labels: dev: Please Review

#4967 Sets fees in all scenarios to 0.
  raiden/tests/scenarios/bf1_basic_functionality.yaml
  raiden/tests/scenarios/ms1_simple_monitoring.yaml
  raiden/tests/scenarios/ms2_simple_monitoring.yaml
  raiden/tests/scenarios/ms3_simple_monitoring.yaml
  raiden/tests/scenarios/ms4_udc_too_low.yaml
  raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
  raiden/tests/scenarios/pfs2_simple_no_path.yaml
  raiden/tests/scenarios/pfs3_multiple_paths.yaml
  raiden/tests/scenarios/pfs4_use_best_path.yaml
  raiden/tests/scenarios/pfs5_too_low_capacity.yaml
  raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
  raiden/tests/scenarios/pfs7_multiple_payments.yaml
  raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
  raiden/tests/scenarios/pfs9_partial_withdraw.yaml
Labels: scenario player

#4968 Document "wormhole attack"
  docs/overview_and_guide.rst
Labels: dev: Please Review

#4950 Add proportional fees scenario [skip tests]
  raiden/tests/scenarios/README.md
  raiden/tests/scenarios/mfee2_proportional_fees.yaml
Labels: dev: Please Review

#4954 The post-failure checks happen at the end of the failing block, not at the beginning.
  docs/proxies.rst
Labels: dev: Work In Progress
