Repository raiden-network/raiden, pull requests merged in 2019-01, with the labels that each got.

#3215 Update WebUI tutorial
  docs/webui_tutorial.rst
Labels: dev: Please Review

#3212 Handle the Parity Transaction already imported error
  docs/changelog.rst
  raiden/network/rpc/client.py
  raiden/network/rpc/smartcontract_proxy.py
Labels: dev: Please Review

#3213 Remove unused get_channelstate_for_receiving()
  raiden/transfer/views.py
Labels: dev: Please Review

#3220 consistent usage of the typing module
  CONTRIBUTING.md
  raiden/transfer/balance_proof.py
  raiden/transfer/channel.py
  raiden/transfer/events.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/initiator_manager.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/state_change.py
  raiden/transfer/mediated_transfer/target.py
  raiden/transfer/node.py
  raiden/transfer/queue_identifier.py
  raiden/transfer/secret_registry.py
  raiden/transfer/state.py
  raiden/transfer/state_change.py
  raiden/transfer/utils.py
  raiden/transfer/views.py
Labels: dev: Please Review

#3218 Finish test_different_view_of_last_bp_during_unlock and address related issues
  docs/changelog.rst
  raiden/network/proxies/token_network.py
  raiden/raiden_service.py
  raiden/tasks.py
  raiden/tests/integration/transfer/test_refundtransfer.py
Labels: dev: Please Review

#3224 Target sanity check
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review

#3226 Upgrade to constantinople enabled Geth
  .circleci/config.yml
  .travis.yml
  tools/testnet/files/dockerfiles/geth-testnet/Dockerfile
Labels: dev: Please Review

#3225 Add missing types in raiden service
  raiden/raiden_service.py
  raiden/transfer/views.py
Labels: dev: Please Review

#3191 Protect targets_to_identifiers_to_statuses with a lock
  docs/changelog.rst
  raiden/raiden_event_handler.py
  raiden/raiden_service.py
Labels: dev: Please Review

#3230 State change handling of alarm task's first run should generate no events
  raiden/raiden_service.py
  raiden/tasks.py
  raiden/tests/integration/transfer/test_refundtransfer.py
Labels: dev: Please Review

#3239 [tools] Add support for value replacements to json-to-html debugging tool
  tools/debugging/json-log-to-html.py
Labels: dev: Please Review

#3240 Add v0.100.2-rc1 to the changelog
  docs/changelog.rst
Labels: dev: Please Review

#3219 Remove mypy errors around SendSecretReveal
  Makefile
  raiden/transfer/events.py
  raiden/transfer/mediated_transfer/events.py
  raiden/transfer/mediated_transfer/mediator.py
  raiden/transfer/mediated_transfer/state.py
Labels: dev: Please Review

#3231 Upgrade scenarioplayer's pyyaml dependency
  tools/scenario-player/requirements.txt
Labels: dev: Please Review

#3248 removed direct payment type
  raiden/raiden_service.py
Labels: dev: Please Review

#3258 Fix API query for channel list without a partner address
  docs/changelog.rst
  raiden/tests/unit/api/test_api.py
  raiden/transfer/views.py
Labels: dev: Please Review

#3261 Bump to v0.100.2-rc2
  .bumpversion_client.cfg
  docs/changelog.rst
  docs/conf.py
  setup.py
Labels: dev: Please Review

#3251 Clarified the SecretRequest meaning
  docs/onboarding.rst
Labels: dev: Please Review

#3269 Removed unecessary default
  raiden/network/proxies/token_network.py
  raiden/tests/integration/contracts/test_token_network.py
Labels: dev: Please Review

#3272 Minor renaming, typos and docs
  raiden/network/transport/udp/udp_transport.py
  raiden/tests/integration/transfer/test_refundtransfer.py
  raiden/tests/utils/protocol.py
Labels: dev: Please Review

#3242 Adds pathfinding service address as CLI argument and stores in config
  raiden/app.py
  raiden/ui/app.py
  raiden/ui/cli.py
Labels: dev: Please Review

#3250 Introduced templates for PRs
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/refactoring.md
Labels: dev: Please Review

#3277 replay_wal.py: changed command line arguments
  tools/debugging/replay_wal.py
Labels: dev: Please Review

#3256 More new factories for unit tests
  raiden/tests/unit/test_sqlite.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate_regression.py
  raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
  raiden/tests/utils/factories.py
Labels: dev: Please Review, testing

#3264 Fuzz testing, Part 2
  raiden/settings.py
  raiden/tests/unit/fuzz/test_state_changes.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/initiator.py
  requirements-dev.txt
Labels: dev: Work In Progress, testing

#3274 Documented different lock status
  raiden/transfer/state.py
Labels: dev: Please Review

#3284 Add pytest option for gevent monitoring signal
  raiden/tests/conftest.py
Labels: dev: Please Review

#3288 ignore mypy output [skip ci]
  .gitignore
Labels: dev: Please Review

#3172 Integrate Synapse into dev requirements
  .circleci/config.yml
  .travis.yml
  .travis/before_install.sh
  .travis/run_smoketest.sh
  constraints.txt
  raiden/network/transport/matrix.py
  raiden/network/utils.py
  raiden/tests/README.rst
  raiden/tests/conftest.py
  raiden/tests/fixtures/variables.py
  raiden/tests/integration/api/test_pythonapi.py
  raiden/tests/integration/conftest.py
  raiden/tests/integration/fixtures/raiden_network.py
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/test_matrix_transport.py
  raiden/tests/integration/test_regression.py
  raiden/tests/unit/test_udp_transport.py
  raiden/tests/utils/geth.py
  raiden/tests/utils/network.py
  raiden/tests/utils/smoketest.py
  raiden/tests/utils/synapse_config.yaml.template
  raiden/tests/utils/transport.py
  raiden/ui/cli.py
  raiden/utils/http.py
  requirements-dev.txt
  setup.cfg
  tools/install_synapse.sh
  tox.ini
Labels: dev: Please Review, matrix

#3289 Adds max paths to be requested as CLI argument and stores in config
  raiden/app.py
  raiden/ui/app.py
  raiden/ui/cli.py
Labels: dev: Please Review

#3280 Additional details in logging for debugging
  raiden/raiden_event_handler.py
Labels: dev: Please Review

#3287 simplified lock acquision in the python api
  raiden/api/python.py
  raiden/network/proxies/payment_channel.py
Labels: dev: Please Review

#3267 CircleCI coverage
  .circleci/config.yml
  .travis.yml
  raiden/tests/fuzz/conftest.py
  raiden/tests/fuzz/test_state_changes.py
  setup.cfg
Labels: dev: Please Review, infrastructure

#3286 removed mention to nonexisting exception [skip ci]
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#3293 Unskip test that was skipped for Travis builds
  raiden/tests/integration/transfer/test_mediatedtransfer.py
Labels: backlog, dev: Please Review, testing

#3296 Fixed removed expired lock message
  raiden/tests/unit/test_channelstate.py
  raiden/transfer/channel.py
Labels: dev: Please Review

#3300 Fix smoketest failure at keyboard interruption
  raiden/tasks.py
  raiden/ui/cli.py
Labels: dev: Please Review

#3295 Target must register secret onchain once only
  raiden/tests/unit/transfer/mediated_transfer/test_targetstate.py
  raiden/transfer/mediated_transfer/state.py
  raiden/transfer/mediated_transfer/target.py
Labels: dev: Please Review

#3305 Fix travis.yml
  .travis.yml
Labels: dev: Please Review

#3140 Split tests on Circle CI by test function instead of file
  .circleci/config.yml
  raiden/tests/conftest.py
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/utils/geth.py
  requirements-dev.txt
Labels: dev: Please Review, testing

#3298 Added asserts on balance proofs
  raiden/tests/unit/transfer/mediated_transfer/test_initiatorstate.py
  raiden/tests/unit/transfer/mediated_transfer/test_mediatorstate.py
  raiden/transfer/channel.py
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/mediated_transfer/mediator.py
Labels: dev: Please Review

#3310 added test docs [skip ci]
  raiden/tests/integration/test_balance_proof_check.py
Labels: dev: Please Review

#3314 removed duplicated utility to compare dicts
  raiden/tests/integration/api/test_restapi.py
  raiden/tests/utils/__init__.py
  raiden/tests/utils/events.py
Labels: dev: Please Review

#3313 removed dulicated tool to wait for block
  raiden/tests/integration/contracts/test_payment_channel.py
  raiden/tests/integration/contracts/test_token_network.py
  raiden/tests/utils/__init__.py
Labels: dev: Please Review

#3308 Don't install pyinstaller and s3cmd in jobs that don't need it
  .travis.yml
  .travis/install.sh
Labels: dev: Please Review

#3307 pr review
  raiden/transfer/utils.py
Labels: dev: Please Review

#3316 Fix race condition in tests
  raiden/tests/integration/test_recovery.py
Labels: dev: Please Review

#3309 Fix test_secret_revealed
  raiden/tests/integration/long_running/test_integration_events.py
  raiden/tests/utils/protocol.py
Labels: dev: Please Review

#3270 remove exceptions from state machines
  raiden/transfer/mediated_transfer/initiator.py
  raiden/transfer/node.py
  raiden/transfer/token_network.py
Labels: dev: Please Review

#3279 Added docker installation guide
  docs/overview_and_guide.rst
Labels: dev: Please Review

#3323 explain `if True:` [skip ci]
  raiden/tests/conftest.py
Labels: dev: Please Review

#3322 tests: fixed logging path
  raiden/tests/conftest.py
  raiden/tests/unit/test_logging.py
Labels: dev: Please Review

#3325 Update webui to v0.8.0
  constraints.txt
  docs/changelog.rst
  docs/images/raiden_webui_channels_page_screenshot.png
  docs/images/raiden_webui_landing_page_screenshot.png
  docs/images/raiden_webui_tokens_page_screenshot.png
Labels: dev: Please Review

#3324 removed unused code
  raiden/tests/conftest.py
Labels: dev: Please Review

#3330 removed poc release [skip ci]
  prepare_poc_release.sh
Labels: dev: Please Review

#3328 removed ugly if True hack
  raiden/tests/conftest.py
Labels: dev: Please Review

#3329 removed unused file
  .bumpversion_contracts.cfg
Labels: dev: Please Review

#3327 pylint: enable unused-variable
  .pylint.rc
  raiden/network/upnpsock.py
  raiden/tests/integration/api/test_restapi.py
  raiden/tests/integration/test_matrix_transport.py
  raiden/tests/unit/test_pfs_integration.py
  raiden/tests/unit/test_tokennetwork.py
Labels: dev: Please Review

#3332 fix: getChannelIdentifier cannot return empty
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#3292 Migrate deployment tasks to CircleCI
  .circleci/config.yml
  .circleci/get_archive_tag.sh
  .circleci/upload_to_s3.sh
  .dockerignore
  .travis.yml
  .travis/homebrew-raiden_github_deploy.enc
  .travis/update_formula.sh
  Makefile
  docker/build.Dockerfile
  raiden.spec
Labels: dev: Please Review, infrastructure

#3334 Fixed unreachable checks
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#3338 Note about safe usage of close [skip ci]
  raiden/network/proxies/token_network.py
Labels: dev: Please Review

#3353 Add disclaimer to the docs [skip ci]
  docs/index.rst
Labels: dev: Please Review

#3359 Don't use deprecated yield fixtures
  raiden/tests/unit/test_accounts.py
Labels: dev: Please Review, test review item

#3358 Remove unused function in test_mtree.py
  raiden/tests/unit/test_mtree.py
Labels: dev: Please Review, test review item

#3360 Rename test_api_server to api_server_test_instance
  raiden/tests/integration/api/fixtures.py
  raiden/tests/integration/api/test_restapi.py
Labels: dev: Please Review, test review item

#3361 fixing grammer in one sentence [skip ci]
  docs/api_walkthrough.rst
Labels: dev: Please Review

#3365 Add note about PR reviews on Contributing.MD
  CONTRIBUTING.md
Labels: dev: Please Review

#3367 Remove unnecessary **kwargs from cli
  raiden/ui/cli.py
Labels: dev: Please Review

#3368 Swap skip ci with skip tests in contributing.md
  CONTRIBUTING.md
Labels: dev: Please Review

#3371 Fix circleci build
  .circleci/conditional_skip.sh
Labels: dev: Please Review
