Repository raiden-network/raiden, pull requests merged in 2020-01, with the labels that each got.

#5552 Ignore Matrix servers with non 2xx HTTP status
  raiden/network/utils.py
  raiden/tests/unit/fixtures.py
  raiden/tests/unit/test_utils.py
  requirements/requirements-ci.txt
  requirements/requirements-dev.in
  requirements/requirements-dev.txt
  requirements/requirements-docs.txt
  requirements/requirements.txt
Labels: PR / Awaiting Review

#5343 Don't listen on broadcast rooms even when invited
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/transport.py
  raiden/settings.py
  raiden/tests/integration/fixtures/transport.py
  raiden/tests/integration/network/transport/test_matrix_transport.py
Labels: Component / Transport, PR / Awaiting Review, Type / Optimization, [SP 2]

#5641 Updates private network deployment guide
  docs/private_net_tutorial.rst
Labels: PR / Awaiting Review

#5572 Remove use of Matrix "account_data"
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/transport.py
  raiden/tests/mocked/test_matrix_transport.py
  raiden/tests/utils/transport.py
Labels: PR / Work In Progress

#5668 Log the transport queue event processing lag
  raiden/network/transport/matrix/client.py
  raiden/network/transport/matrix/transport.py
  raiden/utils/notifying_queue.py
Labels: PR / Awaiting Review

#5660 Fix Matrix server sorting
  raiden/network/transport/matrix/utils.py
  raiden/network/utils.py
  raiden/tests/unit/test_matrix_transport.py
  raiden/tests/unit/test_utils.py
Labels: PR / Awaiting Review

#5686 Improve the script to extract logs
  tools/debugging/extract_sp_exceptions.sh
Labels: PR / Awaiting Review

#5539 Duplicate Scenarios for Ansible Testruns
  raiden/tests/scenarios/bf1_basic_functionality.yaml
  raiden/tests/scenarios/bf2_long_running.yaml
  raiden/tests/scenarios/bf3_multi_directional_payment.yaml
  raiden/tests/scenarios/bf4_multi_payments_same_node.yaml
  raiden/tests/scenarios/bf5_join_and_leave.yaml
  raiden/tests/scenarios/bf6_stress_hub_node.yaml
  raiden/tests/scenarios/bf7_long_path.yaml
  raiden/tests/scenarios/mfee1_flat_fee.yaml
  raiden/tests/scenarios/mfee2_proportional_fees.yaml
  raiden/tests/scenarios/mfee3_only_imbalance_fees.yaml
  raiden/tests/scenarios/mfee4_combined_fees.yaml
  raiden/tests/scenarios/ms1_simple_monitoring.yaml
  raiden/tests/scenarios/ms2_simple_monitoring.yaml
  raiden/tests/scenarios/ms3_simple_monitoring.yaml
  raiden/tests/scenarios/ms4_udc_too_low.yaml
  raiden/tests/scenarios/pfs1_get_a_simple_path.yaml
  raiden/tests/scenarios/pfs2_simple_no_path.yaml
  raiden/tests/scenarios/pfs3_multiple_paths.yaml
  raiden/tests/scenarios/pfs4_use_best_path.yaml
  raiden/tests/scenarios/pfs5_too_low_capacity.yaml
  raiden/tests/scenarios/pfs6_simple_path_rewards.yaml
  raiden/tests/scenarios/pfs7_multiple_payments.yaml
  raiden/tests/scenarios/pfs8_mediator_goes_offline.yaml
  raiden/tests/scenarios/pfs9_partial_withdraw.yaml
Labels: PR / Work In Progress

#5705 Extract SP logs - Part 2
  tools/debugging/extract_sp_exceptions.sh
Labels: PR / Awaiting Review

#5750 Make `RetriableMessage` inherit from `Message`
  raiden/messages/abstract.py
  raiden/network/transport/matrix/transport.py
Labels: PR / Awaiting Review

#5758 Add more performance logging to the MatrixTransport
  raiden/network/transport/matrix/transport.py
  raiden/network/transport/matrix/utils.py
  raiden/tests/unit/test_matrix_transport.py
Labels: PR / Awaiting Review

#5773 More logging in GMatrixClient.sync
  raiden/network/transport/matrix/client.py
Labels: PR / Awaiting Review

#5775 Upgrade cryptography to 2.8
  requirements/requirements-ci.txt
  requirements/requirements-dev.txt
Labels: PR / Awaiting Review
